# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mask.diagnose.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13mask.diagnose.proto\x12\x12MaskDiagnosisProto\"g\n\rMaskDiagnosis\x12\x12\n\ntime_stamp\x18\x01 \x01(\x01\x12\x16\n\x0e\x64iagnosis_code\x18\x02 \x01(\r\x12\x16\n\x0e\x64iagnosis_info\x18\x03 \x01(\t\x12\x12\n\nheartbeart\x18\x04 \x01(\r*\xee\x01\n\x12\x43\x61meraMaskDiagnose\x12\x16\n\x12MASK_DIAG_NO_ERROR\x10\x00\x12\x17\n\x13MASK_DIAG_MEM_ERROR\x10\x01\x12\x16\n\x12MASK_DIAG_MSG_FULL\x10\x02\x12\x17\n\x13MASK_DIAG_CPU_ERROR\x10\x04\x12\x1b\n\x17MASK_DIAG_INPUT_FPS_LOW\x10\x08\x12\x1c\n\x18MASK_DIAG_INPUT_FPS_HIGH\x10\x10\x12\x1c\n\x18MASK_DIAG_OUTPUT_FPS_LOW\x10 \x12\x1d\n\x19MASK_DIAG_DROP_FRAME_MUCH\x10@b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mask.diagnose_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CAMERAMASKDIAGNOSE._serialized_start=149
  _CAMERAMASKDIAGNOSE._serialized_end=387
  _MASKDIAGNOSIS._serialized_start=43
  _MASKDIAGNOSIS._serialized_end=146
# @@protoc_insertion_point(module_scope)
