# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Basc_RemoteMove.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Common_pb2 as Common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x42\x61sc_RemoteMove.proto\x12\x03Soa\x1a\x0c\x43ommon.proto\"G\n)PB_Basc_RemoteMove_RR_ScreenCoordinate_In\x12\x0c\n\x04Xapp\x18\x01 \x01(\r\x12\x0c\n\x04Yapp\x18\x02 \x01(\r\"C\n\"PB_Basc_RemoteMove_RR_FunSwitch_In\x12\r\n\x05State\x18\x01 \x01(\r\x12\x0e\n\x06RoomId\x18\x02 \x01(\x0c\"=\n*PB_Basc_RemoteMove_RR_ScreenCoordinate_Out\x12\x0f\n\x07return_\x18\x01 \x01(\r\"6\n#PB_Basc_RemoteMove_RR_FunSwitch_Out\x12\x0f\n\x07return_\x18\x01 \x01(\rb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Basc_RemoteMove_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PB_BASC_REMOTEMOVE_RR_SCREENCOORDINATE_IN._serialized_start=44
  _PB_BASC_REMOTEMOVE_RR_SCREENCOORDINATE_IN._serialized_end=115
  _PB_BASC_REMOTEMOVE_RR_FUNSWITCH_IN._serialized_start=117
  _PB_BASC_REMOTEMOVE_RR_FUNSWITCH_IN._serialized_end=184
  _PB_BASC_REMOTEMOVE_RR_SCREENCOORDINATE_OUT._serialized_start=186
  _PB_BASC_REMOTEMOVE_RR_SCREENCOORDINATE_OUT._serialized_end=247
  _PB_BASC_REMOTEMOVE_RR_FUNSWITCH_OUT._serialized_start=249
  _PB_BASC_REMOTEMOVE_RR_FUNSWITCH_OUT._serialized_end=303
# @@protoc_insertion_point(module_scope)
