# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Basc_getFileDirRPC.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Common_pb2 as Common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x42\x61sc_getFileDirRPC.proto\x12\x03Soa\x1a\x0c\x43ommon.proto\":\n%PB_Basc_getFileDirRPC_transFileDir_In\x12\x11\n\teventType\x18\x01 \x01(\x0c\"9\n&PB_Basc_getFileDirRPC_transFileDir_Out\x12\x0f\n\x07return_\x18\x01 \x01(\x0c\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Basc_getFileDirRPC_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PB_BASC_GETFILEDIRRPC_TRANSFILEDIR_IN._serialized_start=47
  _PB_BASC_GETFILEDIRRPC_TRANSFILEDIR_IN._serialized_end=105
  _PB_BASC_GETFILEDIRRPC_TRANSFILEDIR_OUT._serialized_start=107
  _PB_BASC_GETFILEDIRRPC_TRANSFILEDIR_OUT._serialized_end=164
# @@protoc_insertion_point(module_scope)
