# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Basc_ADASvoiceCtr.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Common_pb2 as Common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x42\x61sc_ADASvoiceCtr.proto\x12\x03Soa\x1a\x0c\x43ommon.proto\"\x8e\x01\n*PB_Basc_ADASvoiceCtr_RR_HU_VC_ACCactive_In\x12\x36\n\x12HUset_VC_ACCactive\x18\x01 \x01(\x0b\x32\x1a.Soa.PB_HUset_VC_ACCactive\x12(\n\x0bRequestinfo\x18\x02 \x01(\x0b\x32\x13.Soa.PB_RequestInfo\"\xa6\x01\n2PB_Basc_ADASvoiceCtr_RR_HU_VC_CruiseSetDistance_In\x12\x46\n\x1aHUset_VC_CruiseSetDistance\x18\x01 \x01(\x0b\x32\".Soa.PB_HUset_VC_CruiseSetDistance\x12(\n\x0bRequestInfo\x18\x02 \x01(\x0b\x32\x13.Soa.PB_RequestInfo\"\x9d\x01\n/PB_Basc_ADASvoiceCtr_RR_HU_VC_CruiseSetSpeed_In\x12@\n\x17HUset_VC_CruiseSetSpeed\x18\x01 \x01(\x0b\x32\x1f.Soa.PB_HUset_VC_CruiseSetSpeed\x12(\n\x0bRequestInfo\x18\x02 \x01(\x0b\x32\x13.Soa.PB_RequestInfo\"\x91\x01\n+PB_Basc_ADASvoiceCtr_RR_HU_LaneChangeReq_In\x12\x38\n\x13HUset_LaneChangeReq\x18\x01 \x01(\x0b\x32\x1b.Soa.PB_HUset_LaneChangeReq\x12(\n\x0bRequestInfo\x18\x02 \x01(\x0b\x32\x13.Soa.PB_RequestInfo\"T\n+PB_Basc_ADASvoiceCtr_RR_HU_VC_ACCactive_Out\x12%\n\x07return_\x18\x01 \x01(\x0b\x32\x14.Soa.PB_ResponseInfo\"\\\n3PB_Basc_ADASvoiceCtr_RR_HU_VC_CruiseSetDistance_Out\x12%\n\x07return_\x18\x01 \x01(\x0b\x32\x14.Soa.PB_ResponseInfo\"Y\n0PB_Basc_ADASvoiceCtr_RR_HU_VC_CruiseSetSpeed_Out\x12%\n\x07return_\x18\x01 \x01(\x0b\x32\x14.Soa.PB_ResponseInfo\"U\n,PB_Basc_ADASvoiceCtr_RR_HU_LaneChangeReq_Out\x12%\n\x07return_\x18\x01 \x01(\x0b\x32\x14.Soa.PB_ResponseInfob\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Basc_ADASvoiceCtr_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PB_BASC_ADASVOICECTR_RR_HU_VC_ACCACTIVE_IN._serialized_start=47
  _PB_BASC_ADASVOICECTR_RR_HU_VC_ACCACTIVE_IN._serialized_end=189
  _PB_BASC_ADASVOICECTR_RR_HU_VC_CRUISESETDISTANCE_IN._serialized_start=192
  _PB_BASC_ADASVOICECTR_RR_HU_VC_CRUISESETDISTANCE_IN._serialized_end=358
  _PB_BASC_ADASVOICECTR_RR_HU_VC_CRUISESETSPEED_IN._serialized_start=361
  _PB_BASC_ADASVOICECTR_RR_HU_VC_CRUISESETSPEED_IN._serialized_end=518
  _PB_BASC_ADASVOICECTR_RR_HU_LANECHANGEREQ_IN._serialized_start=521
  _PB_BASC_ADASVOICECTR_RR_HU_LANECHANGEREQ_IN._serialized_end=666
  _PB_BASC_ADASVOICECTR_RR_HU_VC_ACCACTIVE_OUT._serialized_start=668
  _PB_BASC_ADASVOICECTR_RR_HU_VC_ACCACTIVE_OUT._serialized_end=752
  _PB_BASC_ADASVOICECTR_RR_HU_VC_CRUISESETDISTANCE_OUT._serialized_start=754
  _PB_BASC_ADASVOICECTR_RR_HU_VC_CRUISESETDISTANCE_OUT._serialized_end=846
  _PB_BASC_ADASVOICECTR_RR_HU_VC_CRUISESETSPEED_OUT._serialized_start=848
  _PB_BASC_ADASVOICECTR_RR_HU_VC_CRUISESETSPEED_OUT._serialized_end=937
  _PB_BASC_ADASVOICECTR_RR_HU_LANECHANGEREQ_OUT._serialized_start=939
  _PB_BASC_ADASVOICECTR_RR_HU_LANECHANGEREQ_OUT._serialized_end=1024
# @@protoc_insertion_point(module_scope)
