# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Basc_ADASStorageTimes.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Common_pb2 as Common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1b\x42\x61sc_ADASStorageTimes.proto\x12\x03Soa\x1a\x0c\x43ommon.proto\"2\n0PB_Basc_ADASStorageTimes_Get_ADASStorageTimes_In\"a\n1PB_Basc_ADASStorageTimes_Get_ADASStorageTimes_Out\x12,\n\x07return_\x18\x01 \x01(\x0b\x32\x1b.Soa.PB_C2_ADASStorageTimesb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Basc_ADASStorageTimes_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PB_BASC_ADASSTORAGETIMES_GET_ADASSTORAGETIMES_IN._serialized_start=50
  _PB_BASC_ADASSTORAGETIMES_GET_ADASSTORAGETIMES_IN._serialized_end=100
  _PB_BASC_ADASSTORAGETIMES_GET_ADASSTORAGETIMES_OUT._serialized_start=102
  _PB_BASC_ADASSTORAGETIMES_GET_ADASSTORAGETIMES_OUT._serialized_end=199
# @@protoc_insertion_point(module_scope)
