# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ca_appendix.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import seq_header_pb2 as seq__header__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x63\x61_appendix.proto\x12\x0clocalization\x1a\x10seq_header.proto\"\xe6\x01\n\nCaAppendix\x12-\n\nseq_header\x18\x01 \x01(\x0b\x32\x19.SeqHeaderProto.SeqHeader\x12\x0f\n\x07heading\x18\x02 \x01(\x01\x12\x12\n\nconfidence\x18\x03 \x01(\x01\x12&\n\x04type\x18\x04 \x01(\x0e\x32\x18.localization.SensorType\x12+\n\nloc_status\x18\x05 \x01(\x0e\x32\x17.localization.LocStatus\x12\x12\n\nfloor_name\x18\x06 \x01(\t\x12\x0c\n\x04roll\x18\x07 \x01(\x01\x12\r\n\x05pitch\x18\x08 \x01(\x01*f\n\nSensorType\x12\x0c\n\x08kUnKnown\x10\x00\x12\x0f\n\x0bkDeadReckon\x10\x01\x12\r\n\tkSemantic\x10\x02\x12\t\n\x05kGnss\x10\x03\x12\x12\n\x0ekVisionFeature\x10\x04\x12\x0b\n\x07kFusion\x10\x14*\x82\x01\n\tLocStatus\x12\x0c\n\x08kInvalid\x10\x00\x12\x12\n\x0ekUninitialized\x10\x01\x12\x0c\n\x08kFailure\x10\x02\x12\x0f\n\x0bkGnssFilter\x10\x03\x12\x14\n\x10kFusionFilterLat\x10\x04\x12\x11\n\rkFusionFilter\x10\x05\x12\x0b\n\x07kRefine\x10\x14\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ca_appendix_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SENSORTYPE._serialized_start=286
  _SENSORTYPE._serialized_end=388
  _LOCSTATUS._serialized_start=391
  _LOCSTATUS._serialized_end=521
  _CAAPPENDIX._serialized_start=54
  _CAAPPENDIX._serialized_end=284
# @@protoc_insertion_point(module_scope)
