# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: compoment_start.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x63ompoment_start.proto\x12\x13\x43ompomentStartProto\"F\n\x0e\x43ompomentStart\x12\x1b\n\x13is_reinjection_mode\x18\x01 \x01(\x08\x12\x17\n\x0f\x63ompoment_start\x18\x02 \x01(\rb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'compoment_start_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _COMPOMENTSTART._serialized_start=46
  _COMPOMENTSTART._serialized_end=116
# @@protoc_insertion_point(module_scope)
