# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: crowd_sourcing_diagnosis.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1e\x63rowd_sourcing_diagnosis.proto\x12\x0clocalization\"\xc7\x01\n\x0b\x43sDiagnosis\x12\x12\n\ntime_stamp\x18\x01 \x01(\x01\x12\x16\n\x0e\x64iagnosis_code\x18\x02 \x01(\r\x12\x33\n\x0emapping_status\x18\x03 \x01(\x0e\x32\x1b.localization.MappingStatus\x12\x16\n\x0e\x64iagnosis_info\x18\x04 \x01(\t\x12\x14\n\x0cstatus_res_1\x18\x05 \x01(\r\x12\x14\n\x0cstatus_res_2\x18\x06 \x01(\t\x12\x13\n\x0bheart_beats\x18\x07 \x01(\r*\x9c\x03\n\x0f\x43sDiagnosisInfo\x12\x13\n\x0fkCsTimeSynFault\x10\x00\x12\x11\n\rkCsInsTimeout\x10\x01\x12\x10\n\x0ckCsFcTimeout\x10\x02\x12\x10\n\x0ckCsScTimeout\x10\x03\x12\x13\n\x0fkCsInsTimeFault\x10\x04\x12\x12\n\x0ekCsFcTimeFault\x10\x05\x12\x12\n\x0ekCsScTimeFault\x10\x06\x12\x15\n\x11kCsInsLonLatFault\x10\x07\x12\x18\n\x14kCsInsOtherDataFault\x10\x08\x12\x15\n\x11kCsWheelDataFault\x10\t\x12\x12\n\x0ekCsFcDataFault\x10\n\x12\x12\n\x0ekCsScDataFault\x10\x0b\x12\x18\n\x14kCsTimeSequenceFault\x10\x0c\x12\x12\n\x0ekCsCutMapFault\x10\r\x12\x15\n\x11kCsPoseGraphFault\x10\x0e\x12\x19\n\x15kCsGroundElementFault\x10\x0f\x12\x16\n\x12kCsAirElementFault\x10\x10\x12\x18\n\x14kCsOtherElementFault\x10\x11*n\n\rMappingStatus\x12\x16\n\x12kMappintProcessing\x10\x00\x12\x14\n\x10kMappingFinished\x10\x01\x12\x13\n\x0fkMappingSuspend\x10\x02\x12\x1a\n\x16kMappingAbnormalTermin\x10\x03\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'crowd_sourcing_diagnosis_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CSDIAGNOSISINFO._serialized_start=251
  _CSDIAGNOSISINFO._serialized_end=663
  _MAPPINGSTATUS._serialized_start=665
  _MAPPINGSTATUS._serialized_end=775
  _CSDIAGNOSIS._serialized_start=49
  _CSDIAGNOSIS._serialized_end=248
# @@protoc_insertion_point(module_scope)
