# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: env_common.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x65nv_common.proto\x12\x0clocalization*@\n\tMapStatus\x12\x0e\n\nkMSUnknown\x10\x00\x12\n\n\x06kHdmap\x10\x01\x12\x0b\n\x07kUexmap\x10\x02\x12\n\n\x06kSdmap\x10\x03*\x92\x02\n\x0bPassageType\x12\x0e\n\nkPTUnknown\x10\x00\x12\r\n\tkStraight\x10\x01\x12\t\n\x05kLeft\x10\x02\x12\n\n\x06kRight\x10\x03\x12\x11\n\rkLeftStraight\x10\x04\x12\x12\n\x0ekRightStraight\x10\x05\x12\x0e\n\nkLeftRight\x10\x06\x12\x16\n\x12kStraightLeftRight\x10\x07\x12\n\n\x06kUturn\x10\x08\x12\x12\n\x0ekStraightUturn\x10\t\x12\x0e\n\nkLeftUturn\x10\n\x12\x0f\n\x0bkRightUturn\x10\x0b\x12\x16\n\x12kStraightLeftUturn\x10\x0c\x12\x13\n\x0fkLeftRightUturn\x10\r\x12\x10\n\x0ckVirtualLane\x10\x0e*I\n\rLaneDirection\x12\x0e\n\nkLDUnknown\x10\x00\x12\x0c\n\x08kForward\x10\x01\x12\x0c\n\x08kReverse\x10\x02\x12\x0c\n\x08kBothWay\x10\x03*<\n\x0bPassability\x12\r\n\tkPUnknown\x10\x00\x12\r\n\tkPassable\x10\x01\x12\x0f\n\x0bkImpassable\x10\x02*[\n\rSlotDirection\x12\x0e\n\nkSDInvalid\x10\x00\x12\x0e\n\nkSDUnknown\x10\x01\x12\r\n\tkVertical\x10\x02\x12\r\n\tkParallel\x10\x03\x12\x0c\n\x08kTilting\x10\x04\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'env_common_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MAPSTATUS._serialized_start=34
  _MAPSTATUS._serialized_end=98
  _PASSAGETYPE._serialized_start=101
  _PASSAGETYPE._serialized_end=375
  _LANEDIRECTION._serialized_start=377
  _LANEDIRECTION._serialized_end=450
  _PASSABILITY._serialized_start=452
  _PASSABILITY._serialized_end=512
  _SLOTDIRECTION._serialized_start=514
  _SLOTDIRECTION._serialized_end=605
# @@protoc_insertion_point(module_scope)
