# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fusion_detection.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x66usion_detection.proto\x12\x0b\x46usionProto\"\xdc\x02\n\x0c\x46usDetection\x12\x1d\n\x15longitudinal_distance\x18\x01 \x01(\x02\x12\x18\n\x10lateral_distance\x18\x02 \x01(\x02\x12\x19\n\x11vertical_distance\x18\x03 \x01(\x02\x12\x0f\n\x07\x61zimuth\x18\x04 \x01(\x02\x12\x17\n\x0f\x65levation_angle\x18\x05 \x01(\x02\x12\x18\n\x10\x65levation_validy\x18\x06 \x01(\x08\x12\x1f\n\x17radial_rel_acceleration\x18\x07 \x01(\x02\x12\x1b\n\x13radial_rel_velocity\x18\x08 \x01(\x02\x12\x1f\n\x17radial_abs_acceleration\x18\t \x01(\x02\x12\x1b\n\x13radial_abs_velocity\x18\n \x01(\x02\x12\x0e\n\x06radius\x18\x0b \x01(\x02\x12\x0b\n\x03rcs\x18\x0c \x01(\x02\x12\x0b\n\x03snr\x18\r \x01(\x02\x12\x0e\n\x06obj_id\x18\x0e \x01(\x05\"N\n\rFusDetections\x12\x12\n\ntime_stamp\x18\x01 \x01(\x01\x12)\n\x06points\x18\x02 \x03(\x0b\x32\x19.FusionProto.FusDetectionb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fusion_detection_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _FUSDETECTION._serialized_start=40
  _FUSDETECTION._serialized_end=388
  _FUSDETECTIONS._serialized_start=390
  _FUSDETECTIONS._serialized_end=468
# @@protoc_insertion_point(module_scope)
