# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fusion_free_space_mcu.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import fusion_common_pb2 as fusion__common__pb2
import seq_header_pb2 as seq__header__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1b\x66usion_free_space_mcu.proto\x12\x0b\x46usionProto\x1a\x13\x66usion_common.proto\x1a\x10seq_header.proto\"\x89\x01\n\x11\x46reeSpacePointMcu\x12*\n\x04type\x18\x01 \x01(\x0e\x32\x1c.FusionCommonProto.PointType\x12\x34\n\x08position\x18\x02 \x01(\x0b\x32\".FusionCommonProto.Point3DPosition\x12\x12\n\nconfidence\x18\x03 \x01(\x05\"\x9a\x01\n\x0f\x46usFreeSpaceMcu\x12\x12\n\ntime_stamp\x18\x01 \x01(\x01\x12.\n\x06points\x18\x02 \x03(\x0b\x32\x1e.FusionProto.FreeSpacePointMcu\x12\x13\n\x0b\x66rame_index\x18\x03 \x01(\x05\x12.\n\tseqheader\x18\x04 \x01(\x0b\x32\x1b.SeqHeaderProto.DelayHeaderb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fusion_free_space_mcu_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _FREESPACEPOINTMCU._serialized_start=84
  _FREESPACEPOINTMCU._serialized_end=221
  _FUSFREESPACEMCU._serialized_start=224
  _FUSFREESPACEMCU._serialized_end=378
# @@protoc_insertion_point(module_scope)
