# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: HDmapdata.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Common_pb2 as Common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fHDmapdata.proto\x12\x03Soa\x1a\x0c\x43ommon.proto\"Z\n\x1dPB_HDmapdata_RR_HDmap_data_In\x12\x0b\n\x03who\x18\x01 \x01(\x0c\x12\x15\n\rserial_number\x18\x02 \x01(\r\x12\x15\n\rcircle_radius\x18\x03 \x01(\x05\"F\n\x1ePB_HDmapdata_RR_HDmap_data_Out\x12$\n\x07return_\x18\x01 \x01(\x0b\x32\x13.Soa.PB_DDSData_Msgb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'HDmapdata_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PB_HDMAPDATA_RR_HDMAP_DATA_IN._serialized_start=38
  _PB_HDMAPDATA_RR_HDMAP_DATA_IN._serialized_end=128
  _PB_HDMAPDATA_RR_HDMAP_DATA_OUT._serialized_start=130
  _PB_HDMAPDATA_RR_HDMAP_DATA_OUT._serialized_end=200
# @@protoc_insertion_point(module_scope)
