# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: header.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cheader.proto\x12\x0clocalization\"`\n\x06Header\x12\x12\n\ntime_stamp\x18\x01 \x01(\x01\x12\x0b\n\x03seq\x18\x02 \x01(\r\x12\x10\n\x08\x66rame_id\x18\x03 \x01(\t\x12\x12\n\ntime_valid\x18\x04 \x01(\x08\x12\x0f\n\x07version\x18\x05 \x01(\tb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'header_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _HEADER._serialized_start=30
  _HEADER._serialized_end=126
# @@protoc_insertion_point(module_scope)
