# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hmi_basic_apafctnsta.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1ahmi_basic_apafctnsta.proto\x12\x0cHmiInterface\"x\n\x10\x41\x44\x41PAFctnStaData\x12\x17\n\x0f\x61\x64_apasysenasta\x18\x01 \x01(\r\x12\x11\n\tad_apasta\x18\x02 \x01(\r\x12\x11\n\tad_rpasta\x18\x03 \x01(\r\x12\x11\n\tad_rmasta\x18\x04 \x01(\r\x12\x12\n\nad_radssta\x18\x05 \x01(\rb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hmi_basic_apafctnsta_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ADAPAFCTNSTADATA._serialized_start=44
  _ADAPAFCTNSTADATA._serialized_end=164
# @@protoc_insertion_point(module_scope)
