# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hmi_basic_slotscene.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19hmi_basic_slotscene.proto\x12\x0cHmiInterface\"(\n\x05Pos3D\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05\x12\t\n\x01z\x18\x03 \x01(\x05\"\x1d\n\x05Pos2D\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05\"\xf2\x01\n\x0b\x45\x44\x43SlotInfo\x12\x0f\n\x07slot_id\x18\x01 \x01(\x05\x12\x12\n\nslot_valid\x18\x02 \x01(\r\x12\x0c\n\x04type\x18\x03 \x01(\r\x12*\n\rvertexes_base\x18\x04 \x03(\x0b\x32\x13.HmiInterface.Pos3D\x12\x16\n\x0elimit_stop_sts\x18\x05 \x01(\r\x12\x10\n\x08lock_sts\x18\x06 \x01(\r\x12-\n\x10limit_stop_start\x18\x07 \x01(\x0b\x32\x13.HmiInterface.Pos2D\x12+\n\x0elimit_stop_end\x18\x08 \x01(\x0b\x32\x13.HmiInterface.Pos2D\"m\n\x0f\x43\x32\x32\x45\x44\x43SlotInfos\x12\x12\n\ntime_stamp\x18\x01 \x01(\x01\x12\x1c\n\x14\x61pa_recommend_slotid\x18\x02 \x01(\x05\x12(\n\x05slots\x18\x03 \x03(\x0b\x32\x19.HmiInterface.EDCSlotInfob\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hmi_basic_slotscene_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _POS3D._serialized_start=43
  _POS3D._serialized_end=83
  _POS2D._serialized_start=85
  _POS2D._serialized_end=114
  _EDCSLOTINFO._serialized_start=117
  _EDCSLOTINFO._serialized_end=359
  _C22EDCSLOTINFOS._serialized_start=361
  _C22EDCSLOTINFOS._serialized_end=470
# @@protoc_insertion_point(module_scope)
