# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: idmap_hmi.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import idmap_common_pb2 as idmap__common__pb2
import idmap_static_pb2 as idmap__static__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fidmap_hmi.proto\x12\x05idmap\x1a\x12idmap_common.proto\x1a\x12idmap_static.proto\"x\n\x0cHMIIDMapInfo\x12\x10\n\x08\x66rom_who\x18\x01 \x01(\t\x12\x1d\n\x15request_serial_number\x18\x02 \x01(\r\x12\x12\n\nerror_code\x18\x03 \x01(\r\x12#\n\nidmap_info\x18\x04 \x01(\x0b\x32\x0f.idmap.HMIIDMap\"\xcc\x01\n\x08HMIIDMap\x12\x1f\n\nanchor_pos\x18\x01 \x01(\x0b\x32\x0b.idmap.Gnss\x12\x15\n\rcircle_radius\x18\x02 \x01(\x05\x12/\n\x0fstatic_map_info\x18\x03 \x01(\x0b\x32\x16.idmap.StaticIDMapInfo\x12\x31\n\x08relation\x18\x04 \x03(\x0b\x32\x1f.idmap.RelativePositionRelation\x12$\n\nlane_group\x18\x05 \x03(\x0b\x32\x10.idmap.LaneGroup\"\xa1\x01\n\x18RelativePositionRelation\x12\x13\n\x0bhmi_lane_id\x18\x01 \x01(\x04\x12\x14\n\x0cleft_line_id\x18\x02 \x03(\x04\x12\x15\n\rright_line_id\x18\x03 \x03(\x04\x12 \n\x18nearest_left_boundary_id\x18\x04 \x01(\x04\x12!\n\x19nearest_right_boundary_id\x18\x05 \x01(\x04\"f\n\tLaneGroup\x12\x15\n\rlane_group_id\x18\x01 \x01(\x04\x12\x14\n\x0clane_id_list\x18\x02 \x03(\x04\x12\x17\n\x0fhmi_boundary_id\x18\x03 \x03(\x04\x12\x13\n\x0bhmi_line_id\x18\x04 \x03(\x04\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'idmap_hmi_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _HMIIDMAPINFO._serialized_start=66
  _HMIIDMAPINFO._serialized_end=186
  _HMIIDMAP._serialized_start=189
  _HMIIDMAP._serialized_end=393
  _RELATIVEPOSITIONRELATION._serialized_start=396
  _RELATIVEPOSITIONRELATION._serialized_end=557
  _LANEGROUP._serialized_start=559
  _LANEGROUP._serialized_end=661
# @@protoc_insertion_point(module_scope)
