# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: idmap_sd_path.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13idmap_sd_path.proto\x12\x05sdmap\"\x1c\n\x04Gnss\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\"P\n\x0cLinkIdentity\x12\r\n\x05ur_id\x18\x01 \x01(\x04\x12\x0f\n\x07tile_id\x18\x02 \x01(\x04\x12\r\n\x05tp_id\x18\x03 \x01(\x04\x12\x11\n\tdirection\x18\x04 \x01(\x08\"\xaf\x02\n\x08LinkInfo\x12%\n\x08link_key\x18\x01 \x01(\x0b\x32\x13.sdmap.LinkIdentity\x12\x1b\n\x06points\x18\x02 \x03(\x0b\x32\x0b.sdmap.Gnss\x12\x13\n\x0blink_length\x18\x03 \x01(\r\x12\x16\n\x0eroad_direction\x18\x04 \x01(\r\x12\x12\n\nroad_class\x18\x05 \x01(\x05\x12\x11\n\tlink_type\x18\x06 \x01(\x05\x12\x17\n\x0froad_attributes\x18\x07 \x01(\x05\x12\x13\n\x0bmain_action\x18\x08 \x01(\x05\x12\x18\n\x10\x61ssistant_action\x18\t \x01(\x05\x12\x1a\n\x12has_parallenl_road\x18\n \x01(\x08\x12\x15\n\rhas_bifurcate\x18\x0b \x01(\x08\x12\x10\n\x08is_valid\x18\x0c \x01(\x08\"Y\n\x0bSegmentInfo\x12\x13\n\x0bsd_is_valid\x18\x01 \x01(\x08\x12\x1e\n\x05links\x18\x02 \x03(\x0b\x32\x0f.sdmap.LinkInfo\x12\x15\n\rspecial_point\x18\x03 \x01(\r\"X\n\x08PathInfo\x12\x15\n\rpath_is_valid\x18\x01 \x01(\x08\x12\x0f\n\x07path_id\x18\x02 \x01(\x04\x12$\n\x08segments\x18\x03 \x03(\x0b\x32\x12.sdmap.SegmentInfo\"E\n\x0bRequestInfo\x12\x12\n\nrequest_id\x18\x01 \x01(\x04\x12\"\n\tpath_info\x18\x02 \x03(\x0b\x32\x0f.sdmap.PathInfob\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'idmap_sd_path_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GNSS._serialized_start=30
  _GNSS._serialized_end=58
  _LINKIDENTITY._serialized_start=60
  _LINKIDENTITY._serialized_end=140
  _LINKINFO._serialized_start=143
  _LINKINFO._serialized_end=446
  _SEGMENTINFO._serialized_start=448
  _SEGMENTINFO._serialized_end=537
  _PATHINFO._serialized_start=539
  _PATHINFO._serialized_end=627
  _REQUESTINFO._serialized_start=629
  _REQUESTINFO._serialized_end=698
# @@protoc_insertion_point(module_scope)
