# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mcu_component_info.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18mcu_component_info.proto\x12\x07McuInfo\"8\n\x10\x43omponentResCost\x12\x11\n\tmem_usage\x18\x01 \x01(\x02\x12\x11\n\tcpu_usage\x18\x02 \x01(\x02\"\xb7\x01\n\x0bMcuCompInfo\x12\x11\n\ttimestamp\x18\x01 \x01(\x01\x12/\n\x0csas_res_cost\x18\x02 \x01(\x0b\x32\x19.McuInfo.ComponentResCost\x12/\n\x0c\x63tl_res_cost\x18\x03 \x01(\x0b\x32\x19.McuInfo.ComponentResCost\x12\x33\n\x10stm_mcu_res_cost\x18\x04 \x01(\x0b\x32\x19.McuInfo.ComponentResCostb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mcu_component_info_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _COMPONENTRESCOST._serialized_start=37
  _COMPONENTRESCOST._serialized_end=93
  _MCUCOMPINFO._serialized_start=96
  _MCUCOMPINFO._serialized_end=279
# @@protoc_insertion_point(module_scope)
