# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: multipose.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import header_pb2 as header__pb2
import odometry_pb2 as odometry__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fmultipose.proto\x12\x0clocalization\x1a\x0cheader.proto\x1a\x0eodometry.proto\"S\n\tMultipose\x12$\n\x06header\x18\x01 \x01(\x0b\x32\x14.localization.Header\x12 \n\x04pose\x18\x02 \x03(\x0b\x32\x12.localization.Poseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'multipose_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MULTIPOSE._serialized_start=63
  _MULTIPOSE._serialized_end=146
# @@protoc_insertion_point(module_scope)
