# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: QueryFilePathInfo.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Common_pb2 as Common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17QueryFilePathInfo.proto\x12\x03Soa\x1a\x0c\x43ommon.proto\"\x82\x01\n-PB_QueryFilePathInfo_Get_QueryFilePathInfo_In\x12\x16\n\x0e\x63ontrollerCode\x18\x01 \x01(\x0c\x12\x12\n\nsearchName\x18\x02 \x01(\x0c\x12\x12\n\nsearchPath\x18\x03 \x01(\x0c\x12\x11\n\tpathDepth\x18\x04 \x01(\x0c\"W\n.PB_QueryFilePathInfo_Get_QueryFilePathInfo_Out\x12%\n\x07return_\x18\x01 \x01(\x0b\x32\x14.Soa.PB_FilePathInfob\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'QueryFilePathInfo_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PB_QUERYFILEPATHINFO_GET_QUERYFILEPATHINFO_IN._serialized_start=47
  _PB_QUERYFILEPATHINFO_GET_QUERYFILEPATHINFO_IN._serialized_end=177
  _PB_QUERYFILEPATHINFO_GET_QUERYFILEPATHINFO_OUT._serialized_start=179
  _PB_QUERYFILEPATHINFO_GET_QUERYFILEPATHINFO_OUT._serialized_end=266
# @@protoc_insertion_point(module_scope)
