# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rnp_debug.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import rnp_common_pb2 as rnp__common__pb2
import seq_header_pb2 as seq__header__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0frnp_debug.proto\x12\x03rnp\x1a\x10rnp_common.proto\x1a\x10seq_header.proto\"\x8d\x02\n\x0bRNPDebugOut\x12-\n\nseq_header\x18\x01 \x01(\x0b\x32\x19.SeqHeaderProto.SeqHeader\x12\x11\n\ttimestamp\x18\x02 \x01(\x01\x12\x32\n\x12runtime_statistics\x18\x03 \x01(\x0b\x32\x16.rnp.RuntimeStatistics\x12@\n\x1ashadow_mode_collected_data\x18\x04 \x01(\x0b\x32\x1c.rnp.ShadowModeCollectedData\x12\'\n\robjects_debug\x18\x05 \x03(\x0b\x32\x10.rnp.ObjectDebug\x12\x1d\n\x15\x61i_activated_scenario\x18\x06 \x01(\r\"C\n\x11RuntimeStatistics\x12\x10\n\x08str_info\x18\x01 \x01(\t\x12\x0c\n\x04keys\x18\x02 \x03(\t\x12\x0e\n\x06values\x18\x03 \x03(\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rnp_debug_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _RNPDEBUGOUT._serialized_start=61
  _RNPDEBUGOUT._serialized_end=330
  _RUNTIMESTATISTICS._serialized_start=332
  _RUNTIMESTATISTICS._serialized_end=399
# @@protoc_insertion_point(module_scope)
