# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tcu.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ttcu.proto\x12\x08TcuProto\"S\n\x03Tcu\x12&\n\x08\x61\x63m_info\x18\x01 \x01(\x0b\x32\x14.TcuProto.BusAcmInfo\x12$\n\x07tcu_sts\x18\x02 \x01(\x0b\x32\x13.TcuProto.BusTcuSts\"\x8f\x03\n\nBusAcmInfo\x12\x1f\n\x17\x61\x63m_acm_actuator_status\x18\x01 \x01(\r\x12#\n\x1b\x61\x63m_acm_actuator_status_dct\x18\x02 \x01(\r\x12 \n\x18\x61\x63m_actuator_prnd_status\x18\x03 \x01(\r\x12#\n\x1b\x61\x63m_ap_adriver_interruption\x18\x04 \x01(\r\x12\x1e\n\x16\x61\x63m_apa_request_enable\x18\x05 \x01(\r\x12\x12\n\ntime_stamp\x18\x06 \x01(\x01\x12\x15\n\rmessage_valid\x18\x07 \x01(\r\x12\x11\n\treserved0\x18\x08 \x01(\r\x12\x11\n\treserved1\x18\t \x01(\r\x12\x11\n\treserved2\x18\n \x01(\r\x12\x11\n\treserved3\x18\x0b \x01(\r\x12\x11\n\treserved4\x18\x0c \x01(\r\x12\x11\n\treserved5\x18\r \x01(\r\x12\x11\n\treserved6\x18\x0e \x01(\r\x12\x11\n\treserved7\x18\x0f \x01(\r\x12\x11\n\treserved8\x18\x10 \x01(\r\"\xab\x03\n\tBusTcuSts\x12\x17\n\x0ftcu_actual_gear\x18\x01 \x01(\r\x12\x1d\n\x15tcu_actual_gear_valid\x18\x02 \x01(\r\x12\x1f\n\x17tcu_gear_shift_position\x18\x03 \x01(\r\x12\x1f\n\x17tcu_shift_postion_valid\x18\x04 \x01(\r\x12\x1c\n\x14tcu_shiftin_progress\x18\x05 \x01(\r\x12\"\n\x1atcu_shiftin_progress_valid\x18\x06 \x01(\r\x12 \n\x18tcu_trans_failure_status\x18\x07 \x01(\r\x12\x1d\n\x15tcu_target_gear_valid\x18\x08 \x01(\r\x12\x17\n\x0ftcu_target_gear\x18\t \x01(\r\x12\x12\n\ntime_stamp\x18\n \x01(\x01\x12\x15\n\rmessage_valid\x18\x0b \x01(\r\x12\x11\n\treserved0\x18\x0c \x01(\r\x12\x11\n\treserved1\x18\r \x01(\r\x12\x11\n\treserved2\x18\x0e \x01(\r\x12\x11\n\treserved3\x18\x0f \x01(\r\x12\x11\n\treserved4\x18\x10 \x01(\rb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tcu_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TCU._serialized_start=23
  _TCU._serialized_end=106
  _BUSACMINFO._serialized_start=109
  _BUSACMINFO._serialized_end=508
  _BUSTCUSTS._serialized_start=511
  _BUSTCUSTS._serialized_end=938
# @@protoc_insertion_point(module_scope)
