# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tripsum.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rtripsum.proto\x12\x08\x44rsProto\"\xbd\x03\n\x07TripSum\x12\x17\n\x0f\x61\x64s_total_miles\x18\x01 \x01(\x02\x12\x15\n\rads_nid_miles\x18\x02 \x01(\x02\x12\x1c\n\x14\x61\x64s_safe_fun_tritime\x18\x03 \x01(\r\x12\x17\n\x0f\x61\x64s_aeb_tritime\x18\x04 \x01(\r\x12\x17\n\x0f\x61\x64s_aes_tritime\x18\x05 \x01(\r\x12\x17\n\x0f\x61\x64s_elk_tritime\x18\x06 \x01(\r\x12\x1d\n\x15\x61\x64s_through_ramp_time\x18\x07 \x01(\r\x12%\n\x1d\x61\x64s_through_intersection_time\x18\x08 \x01(\r\x12\x1c\n\x14\x61\x64s_lane_change_time\x18\t \x01(\r\x12\x19\n\x11\x61\x64s_takeover_time\x18\n \x01(\r\x12\x1a\n\x12\x61\x64s_obs_avoid_time\x18\x0b \x01(\r\x12\x1d\n\x15\x61\x64s_nid_longest_miles\x18\x0c \x01(\x02\x12\x14\n\x0c\x61pa_use_time\x18\r \x01(\r\x12\x15\n\rapa_save_time\x18\x0e \x01(\r\x12\x18\n\x10\x63\x32_user_idnumber\x18\x0f \x01(\t\x12\x18\n\x10\x61\x64s_ads_use_time\x18\x10 \x01(\rb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tripsum_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TRIPSUM._serialized_start=28
  _TRIPSUM._serialized_end=473
# @@protoc_insertion_point(module_scope)
