# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vp_real3d_fc.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import vp_obstacle_pb2 as vp__obstacle__pb2
import vp_perception_base_pb2 as vp__perception__base__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12vp_real3d_fc.proto\x12\x0fVpReal3DFcProto\x1a\x11vp_obstacle.proto\x1a\x18vp_perception_base.proto\"\x9f\x01\n\x0cReal3DResult\x12/\n\x0c\x62\x65v_obstacle\x18\x01 \x01(\x0b\x32\x19.VpObstacleProto.Obstacle\x12/\n\timg_3dbox\x18\x02 \x01(\x0b\x32\x1c.VpPerceptionBaseProto.Box3D\x12-\n\x08img_rect\x18\x03 \x01(\x0b\x32\x1b.VpPerceptionBaseProto.Rect\"\x9b\x01\n\rReal3DResults\x12-\n\x06header\x18\x01 \x01(\x0b\x32\x1d.VpPerceptionBaseProto.Header\x12\x0c\n\x04type\x18\x02 \x01(\x05\x12\x17\n\x0f\x63oordinate_type\x18\x03 \x01(\t\x12\x34\n\rreal3d_result\x18\x04 \x03(\x0b\x32\x1d.VpReal3DFcProto.Real3DResult\"t\n\x0bReal3DProto\x12-\n\x06header\x18\x01 \x01(\x0b\x32\x1d.VpPerceptionBaseProto.Header\x12\x36\n\x0ereal3d_results\x18\x02 \x03(\x0b\x32\x1e.VpReal3DFcProto.Real3DResults*6\n\nReal3DType\x12\x0b\n\x07VEHICLE\x10\x00\x12\x0e\n\nPEDESTRIAN\x10\x01\x12\x0b\n\x07\x43YCLIST\x10\x02\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vp_real3d_fc_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REAL3DTYPE._serialized_start=522
  _REAL3DTYPE._serialized_end=576
  _REAL3DRESULT._serialized_start=85
  _REAL3DRESULT._serialized_end=244
  _REAL3DRESULTS._serialized_start=247
  _REAL3DRESULTS._serialized_end=402
  _REAL3DPROTO._serialized_start=404
  _REAL3DPROTO._serialized_end=520
# @@protoc_insertion_point(module_scope)
