# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vp_scan_point.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import vp_perception_base_pb2 as vp__perception__base__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13vp_scan_point.proto\x12\x10VpScanPointProto\x1a\x18vp_perception_base.proto\"\xc7\x02\n\nScanPoints\x12-\n\x06header\x18\n \x01(\x0b\x32\x1d.VpPerceptionBaseProto.Header\x12\x31\n\x0bpts_cam_gnd\x18\x01 \x03(\x0b\x32\x1c.VpPerceptionBaseProto.Point\x12\x12\n\nray_angles\x18\x02 \x03(\x02\x12\x10\n\x08property\x18\x03 \x03(\x05\x12-\n\x07pts_vcs\x18\x05 \x03(\x0b\x32\x1c.VpPerceptionBaseProto.Point\x12-\n\x07pts_img\x18\x06 \x03(\x0b\x32\x1c.VpPerceptionBaseProto.Point\x12\x0e\n\x06\x63\x61m_id\x18\x04 \x01(\x05\x12\x12\n\ntime_stamp\x18\x07 \x01(\x03\x12\x10\n\x08\x66rame_id\x18\x08 \x01(\x05\x12\x0f\n\x07pb_pass\x18\t \x03(\x08\x12\x0c\n\x04\x63onf\x18\x0b \x03(\x02*l\n\x10ParsingLabelType\x12\x19\n\x15ParsingLabelType_Road\x10\x00\x12\x1e\n\x1aParsingLabelType_LaneMarks\x10\x01\x12\x1d\n\x18ParsingLabelType_Invalid\x10\xff\x01')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vp_scan_point_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PARSINGLABELTYPE._serialized_start=397
  _PARSINGLABELTYPE._serialized_end=505
  _SCANPOINTS._serialized_start=68
  _SCANPOINTS._serialized_end=395
# @@protoc_insertion_point(module_scope)
