# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: calib.diagnosis.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x63\x61lib.diagnosis.proto\x12\x13\x43\x61libDiagnosisProto\"g\n\rCaliDiagnosis\x12\x12\n\ntime_stamp\x18\x01 \x01(\x01\x12\x16\n\x0e\x64iagnosis_code\x18\x02 \x01(\r\x12\x16\n\x0e\x64iagnosis_info\x18\x03 \x01(\t\x12\x12\n\nheartbeart\x18\x04 \x01(\r*\xab\x02\n\x19\x43\x61meraCalibrationDiagnose\x12\x1b\n\x17\x43\x41LIBRATION_DIAG_NORMAL\x10\x00\x12 \n\x1c\x43\x41LIBRATION_DIAG_OPEN_FAILED\x10\x01\x12\x1f\n\x1b\x43\x41LIBRATION_DIAG_NEVER_DONE\x10\x02\x12*\n&CALIBRATION_DIAG_CORNER_DETECTE_FAILED\x10\x04\x12\x1b\n\x17\x43\x41LIBRATION_DIAG_FAILED\x10\x08\x12\x1f\n\x1b\x43\x41LIBRATION_DIAG_IMG_FAILED\x10\x10\x12&\n\"CALIBRATION_DIAG_PRECISION_INVALID\x10 \x12\x1c\n\x18\x43\x41LIBRATION_DIAG_INVALID\x10@b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'calib.diagnosis_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CAMERACALIBRATIONDIAGNOSE._serialized_start=152
  _CAMERACALIBRATIONDIAGNOSE._serialized_end=451
  _CALIDIAGNOSIS._serialized_start=46
  _CALIDIAGNOSIS._serialized_end=149
# @@protoc_insertion_point(module_scope)
