# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sc.diagnosis.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12sc.diagnosis.proto\x12\x10ScDiagnosisProto\"e\n\x0bScDiagnosis\x12\x12\n\ntime_stamp\x18\x01 \x01(\x01\x12\x16\n\x0e\x64iagnosis_code\x18\x02 \x01(\r\x12\x16\n\x0e\x64iagnosis_info\x18\x03 \x01(\t\x12\x12\n\nheartbeart\x18\x04 \x01(\rb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sc.diagnosis_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SCDIAGNOSIS._serialized_start=40
  _SCDIAGNOSIS._serialized_end=141
# @@protoc_insertion_point(module_scope)
