# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vp.diagnosis.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12vp.diagnosis.proto\x12\x10VpDiagnosisProto\"Y\n\x0eImageDiagnosis\x12\x37\n\rimgcheck_type\x18\x01 \x01(\x0e\x32 .VpDiagnosisProto.ImageCheckType\x12\x0e\n\x06\x63\x61m_id\x18\x02 \x01(\x05\"\x9c\x01\n\x0bVpDiagnosis\x12\x12\n\ntime_stamp\x18\x01 \x01(\x01\x12\x16\n\x0e\x64iagnosis_code\x18\x02 \x01(\r\x12\x16\n\x0e\x64iagnosis_info\x18\x03 \x01(\t\x12\x12\n\nheartbeart\x18\x04 \x01(\r\x12\x35\n\x0bimage_check\x18\x05 \x03(\x0b\x32 .VpDiagnosisProto.ImageDiagnosis*W\n\tErrorType\x12\x14\n\x10\x45RROR_NOT_HAPPEN\x10\x00\x12\x18\n\x14\x45RROR_IMAGE_NO_INPUT\x10\x01\x12\x1a\n\x16\x45RROR_MESSAGE_BUF_FULL\x10\x02*\x9a\x01\n\x0eImageCheckType\x12\x1c\n\x18WARNING_IMAGE_NOT_HAPPEN\x10\x00\x12\x19\n\x15WARNING_IMAGE_COVERED\x10\x04\x12\x19\n\x15WARNING_IMAGE_BLURRED\x10\x08\x12\x17\n\x13WARNING_IMAGE_GLARE\x10\x10\x12\x1b\n\x17WARNING_IMAGE_NOT_CALIB\x10 *\xea\x02\n\x0bWarningType\x12\x16\n\x12WARNING_NOT_HAPPEN\x10\x00\x12\x13\n\x0fWARNING_FPS_LOW\x10@\x12\x17\n\x12WARNING_DELAY_HIGH\x10\x80\x01\x12\x19\n\x14WARNING_CPU_ABNORMAL\x10\x80\x02\x12\x19\n\x14WARNING_MEM_ABNORMAL\x10\x80\x04\x12\x19\n\x14WARNING_NO_CAN_SPEED\x10\x80\x08\x12!\n\x1cWARNING_NO_CAN_SPEED_TIMEOUT\x10\x80\x10\x12\x1b\n\x16WARNING_NO_CAN_YAWRATE\x10\x80 \x12#\n\x1eWARNING_NO_CAN_YAWRATE_TIMEOUT\x10\x80@\x12\x1e\n\x18WARNING_NO_CAN_LAT_ACCEL\x10\x80\x80\x01\x12\x1d\n\x17WARNING_NO_CAN_LONG_ACC\x10\x80\x80\x02\x12 \n\x1aWARNING_NO_CAN_WHEEL_ANGLE\x10\x80\x80\x04\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vp.diagnosis_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ERRORTYPE._serialized_start=290
  _ERRORTYPE._serialized_end=377
  _IMAGECHECKTYPE._serialized_start=380
  _IMAGECHECKTYPE._serialized_end=534
  _WARNINGTYPE._serialized_start=537
  _WARNINGTYPE._serialized_end=899
  _IMAGEDIAGNOSIS._serialized_start=40
  _IMAGEDIAGNOSIS._serialized_end=129
  _VPDIAGNOSIS._serialized_start=132
  _VPDIAGNOSIS._serialized_end=288
# @@protoc_insertion_point(module_scope)
