# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: CameraParam.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x43\x61meraParam.proto\x12\x0b\x63\x61meraparam\"\x1d\n\x0c\x44istortParam\x12\r\n\x05param\x18\x01 \x03(\x02\"W\n\x0fInstrinsicParam\x12\x0f\n\x07\x66ocal_u\x18\x01 \x01(\x02\x12\x0f\n\x07\x66ocal_v\x18\x02 \x01(\x02\x12\x10\n\x08\x63\x65nter_u\x18\x03 \x01(\x02\x12\x10\n\x08\x63\x65nter_v\x18\x04 \x01(\x02\"h\n\x0e\x45xtrinsicParam\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\t\n\x01z\x18\x03 \x01(\x02\x12\x0b\n\x03yaw\x18\x04 \x01(\x02\x12\r\n\x05pitch\x18\x05 \x01(\x02\x12\x0c\n\x04roll\x18\x06 \x01(\x02\x12\x0b\n\x03\x66ov\x18\x07 \x01(\x02\"1\n\x08VCSParam\x12\x10\n\x08rotation\x18\x01 \x01(\x02\x12\x13\n\x0btranslation\x18\x02 \x01(\x02\x42\"\n com.mx.changan.datacollect.protob\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'CameraParam_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n com.mx.changan.datacollect.proto'
  _DISTORTPARAM._serialized_start=34
  _DISTORTPARAM._serialized_end=63
  _INSTRINSICPARAM._serialized_start=65
  _INSTRINSICPARAM._serialized_end=152
  _EXTRINSICPARAM._serialized_start=154
  _EXTRINSICPARAM._serialized_end=258
  _VCSPARAM._serialized_start=260
  _VCSPARAM._serialized_end=309
# @@protoc_insertion_point(module_scope)
