// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: idmap_parking.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_idmap_5fparking_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_idmap_5fparking_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3020000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3020001 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_idmap_5fparking_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_idmap_5fparking_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_idmap_5fparking_2eproto;
namespace idmap {
class PakingIDMapInfo;
struct PakingIDMapInfoDefaultTypeInternal;
extern PakingIDMapInfoDefaultTypeInternal _PakingIDMapInfo_default_instance_;
}  // namespace idmap
PROTOBUF_NAMESPACE_OPEN
template<> ::idmap::PakingIDMapInfo* Arena::CreateMaybeMessage<::idmap::PakingIDMapInfo>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace idmap {

// ===================================================================

class PakingIDMapInfo final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:idmap.PakingIDMapInfo) */ {
 public:
  inline PakingIDMapInfo() : PakingIDMapInfo(nullptr) {}
  ~PakingIDMapInfo() override;
  explicit PROTOBUF_CONSTEXPR PakingIDMapInfo(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  PakingIDMapInfo(const PakingIDMapInfo& from);
  PakingIDMapInfo(PakingIDMapInfo&& from) noexcept
    : PakingIDMapInfo() {
    *this = ::std::move(from);
  }

  inline PakingIDMapInfo& operator=(const PakingIDMapInfo& from) {
    CopyFrom(from);
    return *this;
  }
  inline PakingIDMapInfo& operator=(PakingIDMapInfo&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PakingIDMapInfo& default_instance() {
    return *internal_default_instance();
  }
  static inline const PakingIDMapInfo* internal_default_instance() {
    return reinterpret_cast<const PakingIDMapInfo*>(
               &_PakingIDMapInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(PakingIDMapInfo& a, PakingIDMapInfo& b) {
    a.Swap(&b);
  }
  inline void Swap(PakingIDMapInfo* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PakingIDMapInfo* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PakingIDMapInfo* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<PakingIDMapInfo>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const PakingIDMapInfo& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const PakingIDMapInfo& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PakingIDMapInfo* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "idmap.PakingIDMapInfo";
  }
  protected:
  explicit PakingIDMapInfo(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kParkingInfoFieldNumber = 1,
  };
  // double parking_info = 1;
  void clear_parking_info();
  double parking_info() const;
  void set_parking_info(double value);
  private:
  double _internal_parking_info() const;
  void _internal_set_parking_info(double value);
  public:

  // @@protoc_insertion_point(class_scope:idmap.PakingIDMapInfo)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  double parking_info_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_idmap_5fparking_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// PakingIDMapInfo

// double parking_info = 1;
inline void PakingIDMapInfo::clear_parking_info() {
  parking_info_ = 0;
}
inline double PakingIDMapInfo::_internal_parking_info() const {
  return parking_info_;
}
inline double PakingIDMapInfo::parking_info() const {
  // @@protoc_insertion_point(field_get:idmap.PakingIDMapInfo.parking_info)
  return _internal_parking_info();
}
inline void PakingIDMapInfo::_internal_set_parking_info(double value) {
  
  parking_info_ = value;
}
inline void PakingIDMapInfo::set_parking_info(double value) {
  _internal_set_parking_info(value);
  // @@protoc_insertion_point(field_set:idmap.PakingIDMapInfo.parking_info)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace idmap

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_idmap_5fparking_2eproto
