// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: seq_header.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_seq_5fheader_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_seq_5fheader_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3020000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3020001 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_seq_5fheader_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_seq_5fheader_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_seq_5fheader_2eproto;
namespace SeqHeaderProto {
class SeqHeader;
struct SeqHeaderDefaultTypeInternal;
extern SeqHeaderDefaultTypeInternal _SeqHeader_default_instance_;
}  // namespace SeqHeaderProto
PROTOBUF_NAMESPACE_OPEN
template<> ::SeqHeaderProto::SeqHeader* Arena::CreateMaybeMessage<::SeqHeaderProto::SeqHeader>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace SeqHeaderProto {

// ===================================================================

class SeqHeader final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:SeqHeaderProto.SeqHeader) */ {
 public:
  inline SeqHeader() : SeqHeader(nullptr) {}
  ~SeqHeader() override;
  explicit PROTOBUF_CONSTEXPR SeqHeader(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  SeqHeader(const SeqHeader& from);
  SeqHeader(SeqHeader&& from) noexcept
    : SeqHeader() {
    *this = ::std::move(from);
  }

  inline SeqHeader& operator=(const SeqHeader& from) {
    CopyFrom(from);
    return *this;
  }
  inline SeqHeader& operator=(SeqHeader&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SeqHeader& default_instance() {
    return *internal_default_instance();
  }
  static inline const SeqHeader* internal_default_instance() {
    return reinterpret_cast<const SeqHeader*>(
               &_SeqHeader_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(SeqHeader& a, SeqHeader& b) {
    a.Swap(&b);
  }
  inline void Swap(SeqHeader* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SeqHeader* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SeqHeader* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<SeqHeader>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const SeqHeader& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const SeqHeader& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SeqHeader* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "SeqHeaderProto.SeqHeader";
  }
  protected:
  explicit SeqHeader(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTimestampSabVehicleFieldNumber = 1,
  };
  // double timestamp_sab_vehicle = 1;
  void clear_timestamp_sab_vehicle();
  double timestamp_sab_vehicle() const;
  void set_timestamp_sab_vehicle(double value);
  private:
  double _internal_timestamp_sab_vehicle() const;
  void _internal_set_timestamp_sab_vehicle(double value);
  public:

  // @@protoc_insertion_point(class_scope:SeqHeaderProto.SeqHeader)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  double timestamp_sab_vehicle_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_seq_5fheader_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// SeqHeader

// double timestamp_sab_vehicle = 1;
inline void SeqHeader::clear_timestamp_sab_vehicle() {
  timestamp_sab_vehicle_ = 0;
}
inline double SeqHeader::_internal_timestamp_sab_vehicle() const {
  return timestamp_sab_vehicle_;
}
inline double SeqHeader::timestamp_sab_vehicle() const {
  // @@protoc_insertion_point(field_get:SeqHeaderProto.SeqHeader.timestamp_sab_vehicle)
  return _internal_timestamp_sab_vehicle();
}
inline void SeqHeader::_internal_set_timestamp_sab_vehicle(double value) {
  
  timestamp_sab_vehicle_ = value;
}
inline void SeqHeader::set_timestamp_sab_vehicle(double value) {
  _internal_set_timestamp_sab_vehicle(value);
  // @@protoc_insertion_point(field_set:SeqHeaderProto.SeqHeader.timestamp_sab_vehicle)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace SeqHeaderProto

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_seq_5fheader_2eproto
