# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: adr_trigger.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x61\x64r_trigger.proto\x12\nAdrTrigger\"/\n\x07Trigger\x12\x10\n\x08\x65vent_id\x18\x01 \x01(\t\x12\x12\n\ntime_stamp\x18\x02 \x01(\x01\"!\n\x0eSignalSnapshot\x12\x0f\n\x07signals\x18\x01 \x01(\t\"\x1f\n\rEventSnapshot\x12\x0e\n\x06\x65vents\x18\x01 \x01(\t\"\xc0\x01\n\x07GpsData\x12\x0b\n\x03lng\x18\x01 \x01(\r\x12\x0b\n\x03lat\x18\x02 \x01(\r\x12\x0c\n\x04\x61lti\x18\x03 \x01(\r\x12\x10\n\x08gps_time\x18\x04 \x03(\r\x12\x0f\n\x07sat_num\x18\x05 \x01(\r\x12\x0f\n\x07heading\x18\x06 \x01(\r\x12\x0e\n\x06status\x18\x07 \x01(\r\x12\n\n\x02ns\x18\x08 \x01(\r\x12\n\n\x02\x65w\x18\t \x01(\r\x12\r\n\x05speed\x18\n \x01(\r\x12\x0f\n\x07\x64\x65\x63line\x18\x0b \x01(\r\x12\x11\n\tdirection\x18\x0c \x01(\r\")\n\x12\x41ndroidEnvironment\x12\x13\n\x0b\x65nvironment\x18\x01 \x01(\rb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'adr_trigger_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TRIGGER._serialized_start=33
  _TRIGGER._serialized_end=80
  _SIGNALSNAPSHOT._serialized_start=82
  _SIGNALSNAPSHOT._serialized_end=115
  _EVENTSNAPSHOT._serialized_start=117
  _EVENTSNAPSHOT._serialized_end=148
  _GPSDATA._serialized_start=151
  _GPSDATA._serialized_end=343
  _ANDROIDENVIRONMENT._serialized_start=345
  _ANDROIDENVIRONMENT._serialized_end=386
# @@protoc_insertion_point(module_scope)
