# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Basc_DDASstatus.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Common_pb2 as Common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x42\x61sc_DDASstatus.proto\x12\x03Soa\x1a\x0c\x43ommon.proto\")\n\'PB_Basc_DDASstatus_Get_DDSAstatusSet_In\"\x8c\x01\n(PB_Basc_DDASstatus_RR_HU_DDSAS_Active_In\x12\x36\n\x12HUSet_DDSAS_Active\x18\x01 \x01(\x0b\x32\x1a.Soa.PB_HUSet_DDSAS_Active\x12(\n\x0bRequestInfo\x18\x02 \x01(\x0b\x32\x13.Soa.PB_RequestInfo\"W\n(PB_Basc_DDASstatus_Get_DDSAstatusSet_Out\x12+\n\x07return_\x18\x01 \x01(\x0b\x32\x1a.Soa.PB_AD_DDSAS_ActiveSet\"R\n)PB_Basc_DDASstatus_RR_HU_DDSAS_Active_Out\x12%\n\x07return_\x18\x01 \x01(\x0b\x32\x14.Soa.PB_ResponseInfob\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Basc_DDASstatus_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PB_BASC_DDASSTATUS_GET_DDSASTATUSSET_IN._serialized_start=44
  _PB_BASC_DDASSTATUS_GET_DDSASTATUSSET_IN._serialized_end=85
  _PB_BASC_DDASSTATUS_RR_HU_DDSAS_ACTIVE_IN._serialized_start=88
  _PB_BASC_DDASSTATUS_RR_HU_DDSAS_ACTIVE_IN._serialized_end=228
  _PB_BASC_DDASSTATUS_GET_DDSASTATUSSET_OUT._serialized_start=230
  _PB_BASC_DDASSTATUS_GET_DDSASTATUSSET_OUT._serialized_end=317
  _PB_BASC_DDASSTATUS_RR_HU_DDSAS_ACTIVE_OUT._serialized_start=319
  _PB_BASC_DDASSTATUS_RR_HU_DDSAS_ACTIVE_OUT._serialized_end=401
# @@protoc_insertion_point(module_scope)
