# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Basc_SDMap.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Common_pb2 as Common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x42\x61sc_SDMap.proto\x12\x03Soa\x1a\x0c\x43ommon.proto\"!\n\x1fPB_Basc_SDMap_Get_NaviStatus_In\"&\n$PB_Basc_SDMap_Get_LNavResidualDis_In\"3\n PB_Basc_SDMap_Get_NaviStatus_Out\x12\x0f\n\x07return_\x18\x01 \x01(\x05\"8\n%PB_Basc_SDMap_Get_LNavResidualDis_Out\x12\x0f\n\x07return_\x18\x01 \x01(\x04\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Basc_SDMap_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PB_BASC_SDMAP_GET_NAVISTATUS_IN._serialized_start=39
  _PB_BASC_SDMAP_GET_NAVISTATUS_IN._serialized_end=72
  _PB_BASC_SDMAP_GET_LNAVRESIDUALDIS_IN._serialized_start=74
  _PB_BASC_SDMAP_GET_LNAVRESIDUALDIS_IN._serialized_end=112
  _PB_BASC_SDMAP_GET_NAVISTATUS_OUT._serialized_start=114
  _PB_BASC_SDMAP_GET_NAVISTATUS_OUT._serialized_end=165
  _PB_BASC_SDMAP_GET_LNAVRESIDUALDIS_OUT._serialized_start=167
  _PB_BASC_SDMAP_GET_LNAVRESIDUALDIS_OUT._serialized_end=223
# @@protoc_insertion_point(module_scope)
