# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Basc_APAAddlObj.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Common_pb2 as Common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x42\x61sc_APAAddlObj.proto\x12\x03Soa\x1a\x0c\x43ommon.proto\")\n\'PB_Basc_APAAddlObj_Get_AD_APAAddlObj_In\"P\n(PB_Basc_APAAddlObj_Get_AD_APAAddlObj_Out\x12$\n\x07return_\x18\x01 \x01(\x0b\x32\x13.Soa.PB_DDSData_Msgb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Basc_APAAddlObj_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PB_BASC_APAADDLOBJ_GET_AD_APAADDLOBJ_IN._serialized_start=44
  _PB_BASC_APAADDLOBJ_GET_AD_APAADDLOBJ_IN._serialized_end=85
  _PB_BASC_APAADDLOBJ_GET_AD_APAADDLOBJ_OUT._serialized_start=87
  _PB_BASC_APAADDLOBJ_GET_AD_APAADDLOBJ_OUT._serialized_end=167
# @@protoc_insertion_point(module_scope)
