# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Basc_VideoRecordServer.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Common_pb2 as Common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1c\x42\x61sc_VideoRecordServer.proto\x12\x03Soa\x1a\x0c\x43ommon.proto\"x\n$PB_Basc_VideoRecordServer_RR_Init_In\x12(\n\x0bRequestInfo\x18\x01 \x01(\x0b\x32\x13.Soa.PB_RequestInfo\x12&\n\nVideoParam\x18\x02 \x01(\x0b\x32\x12.Soa.PB_VideoParam\"a\n%PB_Basc_VideoRecordServer_RR_Uinit_In\x12(\n\x0bRequestInfo\x18\x01 \x01(\x0b\x32\x13.Soa.PB_RequestInfo\x12\x0e\n\x06\x63\x61mera\x18\x02 \x01(\r\"\x92\x01\n0PB_Basc_VideoRecordServer_RR_RequestVideoFile_In\x12(\n\x0bRequestInfo\x18\x01 \x01(\x0b\x32\x13.Soa.PB_RequestInfo\x12\x34\n\x11VideoRequestParam\x18\x02 \x01(\x0b\x32\x19.Soa.PB_VideoRequestParam\"N\n%PB_Basc_VideoRecordServer_RR_Init_Out\x12%\n\x07return_\x18\x01 \x01(\x0b\x32\x14.Soa.PB_ResponseInfo\"O\n&PB_Basc_VideoRecordServer_RR_Uinit_Out\x12%\n\x07return_\x18\x01 \x01(\x0b\x32\x14.Soa.PB_ResponseInfo\"Z\n1PB_Basc_VideoRecordServer_RR_RequestVideoFile_Out\x12%\n\x07return_\x18\x01 \x01(\x0b\x32\x14.Soa.PB_ResponseInfob\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Basc_VideoRecordServer_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PB_BASC_VIDEORECORDSERVER_RR_INIT_IN._serialized_start=51
  _PB_BASC_VIDEORECORDSERVER_RR_INIT_IN._serialized_end=171
  _PB_BASC_VIDEORECORDSERVER_RR_UINIT_IN._serialized_start=173
  _PB_BASC_VIDEORECORDSERVER_RR_UINIT_IN._serialized_end=270
  _PB_BASC_VIDEORECORDSERVER_RR_REQUESTVIDEOFILE_IN._serialized_start=273
  _PB_BASC_VIDEORECORDSERVER_RR_REQUESTVIDEOFILE_IN._serialized_end=419
  _PB_BASC_VIDEORECORDSERVER_RR_INIT_OUT._serialized_start=421
  _PB_BASC_VIDEORECORDSERVER_RR_INIT_OUT._serialized_end=499
  _PB_BASC_VIDEORECORDSERVER_RR_UINIT_OUT._serialized_start=501
  _PB_BASC_VIDEORECORDSERVER_RR_UINIT_OUT._serialized_end=580
  _PB_BASC_VIDEORECORDSERVER_RR_REQUESTVIDEOFILE_OUT._serialized_start=582
  _PB_BASC_VIDEORECORDSERVER_RR_REQUESTVIDEOFILE_OUT._serialized_end=672
# @@protoc_insertion_point(module_scope)
