# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Basc_HZPMapMng.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Common_pb2 as Common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x42\x61sc_HZPMapMng.proto\x12\x03Soa\x1a\x0c\x43ommon.proto\"+\n)PB_Basc_HZPMapMng_Get_AD_HZPMapMngInfo_In\"+\n)PB_Basc_HZPMapMng_Get_AD_HZPMapMnglist_In\"\x8d\x01\n\'PB_Basc_HZPMapMng_RR_EDC_HZPMapMngID_In\x12\x38\n\x13\x45\x44\x43_HZPMapMngIDData\x18\x01 \x01(\x0b\x32\x1b.Soa.PB_EDC_HZPMapMngIDData\x12(\n\x0bRequestInfo\x18\x02 \x01(\x0b\x32\x13.Soa.PB_RequestInfo\"\x93\x01\n)PB_Basc_HZPMapMng_RR_EDC_HZPMapMngOper_In\x12<\n\x15\x45\x44\x43_HZPMapMngOperData\x18\x01 \x01(\x0b\x32\x1d.Soa.PB_EDC_HZPMapMngOperData\x12(\n\x0bRequestInfo\x18\x02 \x01(\x0b\x32\x13.Soa.PB_RequestInfo\"\x8d\x01\n\'PB_Basc_HZPMapMng_RR_EDC_HZPMapDelID_In\x12\x38\n\x13\x45\x44\x43_HZPMapDelIDData\x18\x01 \x01(\x0b\x32\x1b.Soa.PB_EDC_HZPMapDelIDData\x12(\n\x0bRequestInfo\x18\x02 \x01(\x0b\x32\x13.Soa.PB_RequestInfo\"\x8a\x01\n&PB_Basc_HZPMapMng_RR_EDC_HZPMapEdit_In\x12\x36\n\x12\x45\x44\x43_HZPMapEditData\x18\x01 \x01(\x0b\x32\x1a.Soa.PB_EDC_HZPMapEditData\x12(\n\x0bRequestInfo\x18\x02 \x01(\x0b\x32\x13.Soa.PB_RequestInfo\"[\n*PB_Basc_HZPMapMng_Get_AD_HZPMapMngInfo_Out\x12-\n\x07return_\x18\x01 \x01(\x0b\x32\x1c.Soa.PB_AD_HZPMapMngInfoData\"[\n*PB_Basc_HZPMapMng_Get_AD_HZPMapMnglist_Out\x12-\n\x07return_\x18\x01 \x01(\x0b\x32\x1c.Soa.PB_AD_HZPMapMnglistData\";\n(PB_Basc_HZPMapMng_RR_EDC_HZPMapMngID_Out\x12\x0f\n\x07return_\x18\x01 \x01(\r\"=\n*PB_Basc_HZPMapMng_RR_EDC_HZPMapMngOper_Out\x12\x0f\n\x07return_\x18\x01 \x01(\r\";\n(PB_Basc_HZPMapMng_RR_EDC_HZPMapDelID_Out\x12\x0f\n\x07return_\x18\x01 \x01(\r\":\n\'PB_Basc_HZPMapMng_RR_EDC_HZPMapEdit_Out\x12\x0f\n\x07return_\x18\x01 \x01(\rb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Basc_HZPMapMng_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PB_BASC_HZPMAPMNG_GET_AD_HZPMAPMNGINFO_IN._serialized_start=43
  _PB_BASC_HZPMAPMNG_GET_AD_HZPMAPMNGINFO_IN._serialized_end=86
  _PB_BASC_HZPMAPMNG_GET_AD_HZPMAPMNGLIST_IN._serialized_start=88
  _PB_BASC_HZPMAPMNG_GET_AD_HZPMAPMNGLIST_IN._serialized_end=131
  _PB_BASC_HZPMAPMNG_RR_EDC_HZPMAPMNGID_IN._serialized_start=134
  _PB_BASC_HZPMAPMNG_RR_EDC_HZPMAPMNGID_IN._serialized_end=275
  _PB_BASC_HZPMAPMNG_RR_EDC_HZPMAPMNGOPER_IN._serialized_start=278
  _PB_BASC_HZPMAPMNG_RR_EDC_HZPMAPMNGOPER_IN._serialized_end=425
  _PB_BASC_HZPMAPMNG_RR_EDC_HZPMAPDELID_IN._serialized_start=428
  _PB_BASC_HZPMAPMNG_RR_EDC_HZPMAPDELID_IN._serialized_end=569
  _PB_BASC_HZPMAPMNG_RR_EDC_HZPMAPEDIT_IN._serialized_start=572
  _PB_BASC_HZPMAPMNG_RR_EDC_HZPMAPEDIT_IN._serialized_end=710
  _PB_BASC_HZPMAPMNG_GET_AD_HZPMAPMNGINFO_OUT._serialized_start=712
  _PB_BASC_HZPMAPMNG_GET_AD_HZPMAPMNGINFO_OUT._serialized_end=803
  _PB_BASC_HZPMAPMNG_GET_AD_HZPMAPMNGLIST_OUT._serialized_start=805
  _PB_BASC_HZPMAPMNG_GET_AD_HZPMAPMNGLIST_OUT._serialized_end=896
  _PB_BASC_HZPMAPMNG_RR_EDC_HZPMAPMNGID_OUT._serialized_start=898
  _PB_BASC_HZPMAPMNG_RR_EDC_HZPMAPMNGID_OUT._serialized_end=957
  _PB_BASC_HZPMAPMNG_RR_EDC_HZPMAPMNGOPER_OUT._serialized_start=959
  _PB_BASC_HZPMAPMNG_RR_EDC_HZPMAPMNGOPER_OUT._serialized_end=1020
  _PB_BASC_HZPMAPMNG_RR_EDC_HZPMAPDELID_OUT._serialized_start=1022
  _PB_BASC_HZPMAPMNG_RR_EDC_HZPMAPDELID_OUT._serialized_end=1081
  _PB_BASC_HZPMAPMNG_RR_EDC_HZPMAPEDIT_OUT._serialized_start=1083
  _PB_BASC_HZPMAPMNG_RR_EDC_HZPMAPEDIT_OUT._serialized_end=1141
# @@protoc_insertion_point(module_scope)
