# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Basc_HZPMapRS.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Common_pb2 as Common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x42\x61sc_HZPMapRS.proto\x12\x03Soa\x1a\x0c\x43ommon.proto\"#\n!PB_Basc_HZPMapRS_Get_AD_HZPMap_In\"H\n\"PB_Basc_HZPMapRS_Get_AD_HZPMap_Out\x12\"\n\x07return_\x18\x01 \x01(\x0b\x32\x11.Soa.PB_AD_HZPMapb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Basc_HZPMapRS_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PB_BASC_HZPMAPRS_GET_AD_HZPMAP_IN._serialized_start=42
  _PB_BASC_HZPMAPRS_GET_AD_HZPMAP_IN._serialized_end=77
  _PB_BASC_HZPMAPRS_GET_AD_HZPMAP_OUT._serialized_start=79
  _PB_BASC_HZPMAPRS_GET_AD_HZPMAP_OUT._serialized_end=151
# @@protoc_insertion_point(module_scope)
