# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Basc_DCEngineeringModel.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Common_pb2 as Common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1d\x42\x61sc_DCEngineeringModel.proto\x12\x03Soa\x1a\x0c\x43ommon.proto\"\x8e\x01\n*PB_Basc_DCEngineeringModel_Cnr_StopTask_In\x12\x11\n\tstartTIme\x18\x01 \x01(\x0c\x12\x0f\n\x07\x65ndTime\x18\x02 \x01(\x0c\x12\x0e\n\x06taskId\x18\x03 \x01(\x0c\x12,\n\x08\x66ileList\x18\x04 \x01(\x0b\x32\x1a.Soa.PB_DC_FileList_Struct\"Q\n4PB_Basc_DCEngineeringModel_RR_SyncCalibrationFile_In\x12\x0b\n\x03vin\x18\x01 \x01(\x0c\x12\x0c\n\x04tuid\x18\x02 \x01(\x0c\">\n+PB_Basc_DCEngineeringModel_Cnr_StopTask_Out\x12\x0f\n\x07return_\x18\x01 \x01(\r\"H\n5PB_Basc_DCEngineeringModel_RR_SyncCalibrationFile_Out\x12\x0f\n\x07return_\x18\x01 \x01(\rb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Basc_DCEngineeringModel_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PB_BASC_DCENGINEERINGMODEL_CNR_STOPTASK_IN._serialized_start=53
  _PB_BASC_DCENGINEERINGMODEL_CNR_STOPTASK_IN._serialized_end=195
  _PB_BASC_DCENGINEERINGMODEL_RR_SYNCCALIBRATIONFILE_IN._serialized_start=197
  _PB_BASC_DCENGINEERINGMODEL_RR_SYNCCALIBRATIONFILE_IN._serialized_end=278
  _PB_BASC_DCENGINEERINGMODEL_CNR_STOPTASK_OUT._serialized_start=280
  _PB_BASC_DCENGINEERINGMODEL_CNR_STOPTASK_OUT._serialized_end=342
  _PB_BASC_DCENGINEERINGMODEL_RR_SYNCCALIBRATIONFILE_OUT._serialized_start=344
  _PB_BASC_DCENGINEERINGMODEL_RR_SYNCCALIBRATIONFILE_OUT._serialized_end=416
# @@protoc_insertion_point(module_scope)
