# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Basic_APAFunctionReq.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Common_pb2 as Common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1a\x42\x61sic_APAFunctionReq.proto\x12\x03Soa\x1a\x0c\x43ommon.proto\"I\n,PB_Basic_APAFunctionReq_RR_APAFunctionReq_In\x12\x19\n\x11RR_APAFunctionReq\x18\x01 \x01(\r\"E\n,PB_Basic_APAFunctionReq_RR_APAControleReq_In\x12\x15\n\rAPAControlReq\x18\x01 \x01(\r\"X\n*PB_Basic_APAFunctionReq_RR_HeartbeatReq_In\x12*\n\x0cHeartbeatReq\x18\x01 \x01(\x0b\x32\x14.Soa.PB_HeartbeatReq\"U\n-PB_Basic_APAFunctionReq_RR_APAFunctionReq_Out\x12$\n\x07return_\x18\x01 \x01(\x0b\x32\x13.Soa.PB_APAReqreply\"U\n-PB_Basic_APAFunctionReq_RR_APAControleReq_Out\x12$\n\x07return_\x18\x01 \x01(\x0b\x32\x13.Soa.PB_APAReqreply\"S\n+PB_Basic_APAFunctionReq_RR_HeartbeatReq_Out\x12$\n\x07return_\x18\x01 \x01(\x0b\x32\x13.Soa.PB_APAReqreplyb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Basic_APAFunctionReq_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PB_BASIC_APAFUNCTIONREQ_RR_APAFUNCTIONREQ_IN._serialized_start=49
  _PB_BASIC_APAFUNCTIONREQ_RR_APAFUNCTIONREQ_IN._serialized_end=122
  _PB_BASIC_APAFUNCTIONREQ_RR_APACONTROLEREQ_IN._serialized_start=124
  _PB_BASIC_APAFUNCTIONREQ_RR_APACONTROLEREQ_IN._serialized_end=193
  _PB_BASIC_APAFUNCTIONREQ_RR_HEARTBEATREQ_IN._serialized_start=195
  _PB_BASIC_APAFUNCTIONREQ_RR_HEARTBEATREQ_IN._serialized_end=283
  _PB_BASIC_APAFUNCTIONREQ_RR_APAFUNCTIONREQ_OUT._serialized_start=285
  _PB_BASIC_APAFUNCTIONREQ_RR_APAFUNCTIONREQ_OUT._serialized_end=370
  _PB_BASIC_APAFUNCTIONREQ_RR_APACONTROLEREQ_OUT._serialized_start=372
  _PB_BASIC_APAFUNCTIONREQ_RR_APACONTROLEREQ_OUT._serialized_end=457
  _PB_BASIC_APAFUNCTIONREQ_RR_HEARTBEATREQ_OUT._serialized_start=459
  _PB_BASIC_APAFUNCTIONREQ_RR_HEARTBEATREQ_OUT._serialized_end=542
# @@protoc_insertion_point(module_scope)
