# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bev_std.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rbev_std.proto\x12\x0b\x42\x65vStdProto\"\'\n\tTimeStamp\x12\x0c\n\x04msec\x18\x01 \x01(\x03\x12\x0c\n\x04usec\x18\x02 \x01(\x03\"&\n\x08\x44uration\x12\x0c\n\x04msec\x18\x01 \x01(\x03\x12\x0c\n\x04usec\x18\x02 \x01(\x03\"S\n\x06Header\x12\x0b\n\x03seq\x18\x01 \x01(\r\x12*\n\ntime_stamp\x18\x02 \x01(\x0b\x32\x16.BevStdProto.TimeStamp\x12\x10\n\x08\x66rame_id\x18\x03 \x01(\t\"7\n\tColorRGBA\x12\t\n\x01r\x18\x01 \x01(\x02\x12\t\n\x01g\x18\x02 \x01(\x02\x12\t\n\x01\x62\x18\x03 \x01(\x02\x12\t\n\x01\x61\x18\x04 \x01(\x02\"\x1b\n\x0bUInt32Array\x12\x0c\n\x04\x64\x61ta\x18\x01 \x03(\r\"\x1c\n\nBoolStatus\x12\x0e\n\x06status\x18\x01 \x01(\x08*\x97\x02\n\x08\x44\x61taType\x12\x15\n\x11\x44\x41TA_TYPE_UNKNOWN\x10\x00\x12\x12\n\x0e\x44\x41TA_TYPE_BOOL\x10\x01\x12\x14\n\x10\x44\x41TA_TYPE_UINT_8\x10\x02\x12\x13\n\x0f\x44\x41TA_TYPE_INT_8\x10\x03\x12\x15\n\x11\x44\x41TA_TYPE_UINT_16\x10\x04\x12\x14\n\x10\x44\x41TA_TYPE_INT_16\x10\x05\x12\x15\n\x11\x44\x41TA_TYPE_UINT_32\x10\x06\x12\x14\n\x10\x44\x41TA_TYPE_INT_32\x10\x07\x12\x16\n\x12\x44\x41TA_TYPE_FLOAT_32\x10\x08\x12\x15\n\x11\x44\x41TA_TYPE_UINT_64\x10\t\x12\x14\n\x10\x44\x41TA_TYPE_INT_64\x10\n\x12\x16\n\x12\x44\x41TA_TYPE_FLOAT_64\x10\x0b\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bev_std_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DATATYPE._serialized_start=313
  _DATATYPE._serialized_end=592
  _TIMESTAMP._serialized_start=30
  _TIMESTAMP._serialized_end=69
  _DURATION._serialized_start=71
  _DURATION._serialized_end=109
  _HEADER._serialized_start=111
  _HEADER._serialized_end=194
  _COLORRGBA._serialized_start=196
  _COLORRGBA._serialized_end=251
  _UINT32ARRAY._serialized_start=253
  _UINT32ARRAY._serialized_end=280
  _BOOLSTATUS._serialized_start=282
  _BOOLSTATUS._serialized_end=310
# @@protoc_insertion_point(module_scope)
