# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bev_geometry.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import bev_std_pb2 as bev__std__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x62\x65v_geometry.proto\x12\x0b\x42\x65vGeoProto\x1a\rbev_std.proto\"(\n\x05Point\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\t\n\x01z\x18\x03 \x01(\x01\"Y\n\x04Pose\x12$\n\x08position\x18\x01 \x01(\x0b\x32\x12.BevGeoProto.Point\x12+\n\nquaternion\x18\x02 \x01(\x0b\x32\x17.BevGeoProto.Quaternion\"c\n\nQuaternion\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\t\n\x01z\x18\x03 \x01(\x01\x12\t\n\x01w\x18\x04 \x01(\x01\x12)\n\x04type\x18\x05 \x01(\x0e\x32\x1b.BevGeoProto.QuaternionType*G\n\x0eQuaternionType\x12\x1c\n\x18QUATERNION_TYPE_HAMILTON\x10\x00\x12\x17\n\x13QUATERNION_TYPE_JPL\x10\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bev_geometry_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _QUATERNIONTYPE._serialized_start=284
  _QUATERNIONTYPE._serialized_end=355
  _POINT._serialized_start=50
  _POINT._serialized_end=90
  _POSE._serialized_start=92
  _POSE._serialized_end=181
  _QUATERNION._serialized_start=183
  _QUATERNION._serialized_end=282
# @@protoc_insertion_point(module_scope)
