# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: busip.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x62usip.proto\x12\nBusipProto\"\x84\x03\n\x05\x42usIP\x12\x13\n\x0bip_dis_fail\x18\x01 \x01(\r\x12\x1d\n\x15ip_driver_lcdaled_sts\x18\x02 \x01(\r\x12 \n\x18ip_passenger_lcdaled_sts\x18\x03 \x01(\r\x12\x1a\n\x12ip_q_dash_acc_fail\x18\x04 \x01(\r\x12\x12\n\ntime_stamp\x18\x05 \x01(\x01\x12\x13\n\x0b\x63\x64\x63_totmilg\x18\x06 \x01(\x01\x12\x1e\n\x16ipju_ads_sts_e2e_faout\x18\x07 \x01(\r\x12\x1a\n\x12ipju_ads_show_infa\x18\x08 \x01(\r\x12\x1b\n\x13ipju_ads_show_outfa\x18\t \x01(\r\x12\x15\n\rmessage_valid\x18\n \x01(\r\x12\x11\n\treserved0\x18\x0b \x01(\r\x12\x11\n\treserved1\x18\x0c \x01(\r\x12\x11\n\treserved2\x18\r \x01(\r\x12\x11\n\treserved3\x18\x0e \x01(\r\x12\x11\n\treserved4\x18\x0f \x01(\r\x12\x11\n\treserved5\x18\x10 \x01(\rb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'busip_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _BUSIP._serialized_start=28
  _BUSIP._serialized_end=416
# @@protoc_insertion_point(module_scope)
