# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: busims.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x62usims.proto\x12\x0b\x42usimsProto\"\x8b\x06\n\x06\x42usIMS\x12\x1d\n\x15ims_brow_offset_value\x18\x01 \x01(\r\x12\x1e\n\x16ims_distraction_status\x18\x02 \x01(\r\x12\"\n\x1aims_driver_eye_closestatus\x18\x03 \x01(\r\x12 \n\x18ims_driver_eyes_fov_area\x18\x04 \x01(\r\x12\x1e\n\x16ims_driver_head_detect\x18\x05 \x01(\r\x12\x1d\n\x15ims_drowsiness_status\x18\x06 \x01(\r\x12\x1b\n\x13ims_eye_gaze_status\x18\x07 \x01(\x05\x12!\n\x19ims_head_detect_sts_pitch\x18\x08 \x01(\x05\x12 \n\x18ims_head_detect_sts_roll\x18\t \x01(\x05\x12\x1f\n\x17ims_head_detect_sts_yaw\x18\n \x01(\x05\x12\x16\n\x0eims_ims_status\x18\x0b \x01(\r\x12\x1c\n\x14ims_jaw_offset_value\x18\x0c \x01(\r\x12\x1a\n\x12ims_phone_call_sts\x18\r \x01(\r\x12\x12\n\ntime_stamp\x18\x0f \x01(\x01\x12\x1b\n\x13ims_driverbehaviors\x18\x10 \x01(\r\x12\x15\n\rmessage_valid\x18\x11 \x01(\r\x12\x11\n\treserved0\x18\x12 \x01(\r\x12\x11\n\treserved1\x18\x13 \x01(\r\x12\x11\n\treserved2\x18\x14 \x01(\r\x12\x11\n\treserved3\x18\x15 \x01(\r\x12\x11\n\treserved4\x18\x16 \x01(\r\x12\x11\n\treserved5\x18\x17 \x01(\r\x12\x11\n\treserved6\x18\x18 \x01(\r\x12\x11\n\treserved7\x18\x19 \x01(\r\x12\x11\n\treserved8\x18\x1a \x01(\r\x12\x11\n\treserved9\x18\x1b \x01(\r\x12\x12\n\nreserved10\x18\x1c \x01(\r\x12\x12\n\nreserved11\x18\x1d \x01(\r\x12\x12\n\nreserved12\x18\x1e \x01(\r\x12\x12\n\nreserved13\x18\x1f \x01(\r\x12\x12\n\nreserved14\x18  \x01(\rb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'busims_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _BUSIMS._serialized_start=30
  _BUSIMS._serialized_end=809
# @@protoc_insertion_point(module_scope)
