# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: can_diag.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x63\x61n_diag.proto\x12\x0c\x43\x61nDiagProto\"\xda\x03\n\rComFltService\x12-\n\x0c\x61vh_func_sts\x18\x01 \x01(\x0b\x32\x17.CanDiagProto.ComFltSts\x12\x33\n\x12\x62ody_staby_sys_sts\x18\x02 \x01(\x0b\x32\x17.CanDiagProto.ComFltSts\x12(\n\x07\x65pb_fuc\x18\x03 \x01(\x0b\x32\x17.CanDiagProto.ComFltSts\x12,\n\x0b\x65sp_vdc_sts\x18\x04 \x01(\x0b\x32\x17.CanDiagProto.ComFltSts\x12,\n\x0brbm_veh_spd\x18\x05 \x01(\x0b\x32\x17.CanDiagProto.ComFltSts\x12(\n\x07veh_spd\x18\x06 \x01(\x0b\x32\x17.CanDiagProto.ComFltSts\x12\x34\n\x0fsc_calibraction\x18\x07 \x01(\x0b\x32\x1b.CanDiagProto.SCcalibration\x12\x33\n\x0cli_sn_err_st\x18\x08 \x01(\x0b\x32\x1d.CanDiagProto.LiSnsrInfoState\x12\x34\n\x0fhod_detect_info\x18\t \x01(\x0b\x32\x1b.CanDiagProto.HODDetectInfo\x12\x14\n\x0c\x64md_prm_info\x18\n \x01(\r\"Y\n\tComFltSts\x12\x18\n\x10lost_com_flt_sts\x18\x01 \x01(\r\x12\x15\n\rcrc_check_sts\x18\x02 \x01(\r\x12\x1b\n\x13rolling_counter_sts\x18\x03 \x01(\r\"\xae\x01\n\rHODDetectInfo\x12\x15\n\rsystem_status\x18\x01 \x01(\r\x12\x15\n\rsenser_status\x18\x02 \x01(\r\x12\x12\n\napp_status\x18\x03 \x01(\r\x12\x12\n\nlin_status\x18\x04 \x01(\r\x12\x1b\n\x13\x63\x61libraction_status\x18\x05 \x01(\r\x12\x17\n\x0frolling_counter\x18\x06 \x01(\r\x12\x11\n\tcheck_sum\x18\x07 \x01(\r\"\x1e\n\rSCcalibration\x12\r\n\x05state\x18\x01 \x01(\r\"\'\n\x0fLiSnsrInfoState\x12\x14\n\x0cli_sn_err_st\x18\x01 \x01(\rb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'can_diag_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _COMFLTSERVICE._serialized_start=33
  _COMFLTSERVICE._serialized_end=507
  _COMFLTSTS._serialized_start=509
  _COMFLTSTS._serialized_end=598
  _HODDETECTINFO._serialized_start=601
  _HODDETECTINFO._serialized_end=775
  _SCCALIBRATION._serialized_start=777
  _SCCALIBRATION._serialized_end=807
  _LISNSRINFOSTATE._serialized_start=809
  _LISNSRINFOSTATE._serialized_end=848
# @@protoc_insertion_point(module_scope)
