# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: das_uss.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rdas_uss.proto\x12\x0b\x44\x61sUssProto\"\x97\x01\n\x07RawData\x12\x12\n\ntime_stamp\x18\x01 \x01(\x01\x12\x15\n\rrx_time_stamp\x18\x02 \x01(\x01\x12\x15\n\rtx_time_stamp\x18\x03 \x01(\x01\x12\x10\n\x08uss_data\x18\x04 \x01(\x0c\x12\x10\n\x08\x64\x61ta_len\x18\x05 \x01(\x05\x12\x0f\n\x07\x63ounter\x18\x06 \x01(\r\x12\x15\n\rmessage_valid\x18\x07 \x01(\rb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'das_uss_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _RAWDATA._serialized_start=31
  _RAWDATA._serialized_end=182
# @@protoc_insertion_point(module_scope)
