# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: encode_srv.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x65ncode_srv.proto\x12\tEncodeSrv\"\xc0\x01\n\nEncodeH265\x12\r\n\x05\x63\x61mid\x18\x01 \x01(\r\x12\x10\n\x08\x66rame_id\x18\x02 \x01(\x03\x12\x12\n\nframe_size\x18\x03 \x01(\r\x12\x12\n\nframe_data\x18\x04 \x01(\x0c\x12\x12\n\nencodetype\x18\x05 \x01(\r\x12\x14\n\x0c\x65ncode_width\x18\x06 \x01(\r\x12\x15\n\rencode_height\x18\x07 \x01(\r\x12\x15\n\rframe_ratenum\x18\x08 \x01(\r\x12\x11\n\ttimestamp\x18\t \x01(\x04\"i\n\x0f\x45ncodeDiagnosis\x12\x12\n\ntime_stamp\x18\x01 \x01(\x01\x12\x16\n\x0e\x64iagnosis_code\x18\x02 \x01(\r\x12\x16\n\x0e\x64iagnosis_info\x18\x03 \x01(\t\x12\x12\n\nheartbeart\x18\x04 \x01(\r\"z\n\nEncodeJpeg\x12\r\n\x05\x63\x61mid\x18\x01 \x01(\r\x12\x0f\n\x07\x66rameid\x18\x02 \x01(\x03\x12\x11\n\ttimestamp\x18\x03 \x01(\x04\x12\r\n\x05width\x18\x04 \x01(\r\x12\x0e\n\x06height\x18\x05 \x01(\r\x12\x0c\n\x04size\x18\x06 \x01(\r\x12\x0c\n\x04\x64\x61ta\x18\x07 \x01(\x0c\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'encode_srv_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ENCODEH265._serialized_start=32
  _ENCODEH265._serialized_end=224
  _ENCODEDIAGNOSIS._serialized_start=226
  _ENCODEDIAGNOSIS._serialized_end=331
  _ENCODEJPEG._serialized_start=333
  _ENCODEJPEG._serialized_end=455
# @@protoc_insertion_point(module_scope)
