# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fusion_image_box.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import fusion_common_pb2 as fusion__common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x66usion_image_box.proto\x12\x0b\x46usionProto\x1a\x13\x66usion_common.proto\"\xa8\x01\n\x0e\x46usionImageBox\x12\x14\n\x0c\x63\x61m_track_id\x18\x01 \x01(\x05\x12%\n\x04rect\x18\x02 \x01(\x0b\x32\x17.FusionCommonProto.Rect\x12\x16\n\x0elidar_track_id\x18\x03 \x01(\x05\x12-\n\x06points\x18\x04 \x03(\x0b\x32\x1d.FusionCommonProto.PixelPoint\x12\x12\n\ncam_source\x18\x05 \x01(\x05\"\x83\x01\n\x0f\x46usionImageBoxs\x12\x0e\n\x06\x63\x61m_id\x18\x01 \x01(\x05\x12\x12\n\ntime_stamp\x18\x02 \x01(\x01\x12\x37\n\x12\x66usion_image_boxes\x18\x03 \x03(\x0b\x32\x1b.FusionProto.FusionImageBox\x12\x13\n\x0b\x66rame_index\x18\x04 \x01(\x05\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fusion_image_box_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _FUSIONIMAGEBOX._serialized_start=61
  _FUSIONIMAGEBOX._serialized_end=229
  _FUSIONIMAGEBOXS._serialized_start=232
  _FUSIONIMAGEBOXS._serialized_end=363
# @@protoc_insertion_point(module_scope)
