# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fusion_object_mcu.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import fusion_common_pb2 as fusion__common__pb2
import seq_header_pb2 as seq__header__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x66usion_object_mcu.proto\x12\x0b\x46usionProto\x1a\x13\x66usion_common.proto\x1a\x10seq_header.proto\"\xcd\x06\n\x0c\x46usObjectMcu\x12\x10\n\x08track_id\x18\x01 \x01(\x05\x12\x1d\n\x15longitudinal_distance\x18\x02 \x01(\x02\x12\x18\n\x10lateral_distance\x18\x03 \x01(\x02\x12&\n\x1elongitudinal_absolute_velocity\x18\x04 \x01(\x02\x12!\n\x19lateral_absolute_velocity\x18\x05 \x01(\x02\x12*\n\"longitudinal_absolute_acceleration\x18\x06 \x01(\x02\x12%\n\x1dlateral_absolute_acceleration\x18\x07 \x01(\x02\x12\x0e\n\x06length\x18\x08 \x01(\x02\x12\r\n\x05width\x18\t \x01(\x02\x12\r\n\x05heigh\x18\n \x01(\x02\x12\x15\n\rheading_angle\x18\x0b \x01(\x02\x12\x36\n\x0e\x63lassification\x18\x0c \x01(\x0e\x32\x1e.FusionCommonProto.ObjectClass\x12\x15\n\rdetect_sensor\x18\r \x01(\r\x12\x12\n\nconfidence\x18\x0e \x01(\x05\x12\x0b\n\x03\x61ge\x18\x0f \x01(\x05\x12\x17\n\x0f\x63ross_line_flag\x18\x10 \x01(\x08\x12\x18\n\x10\x63ross_line_value\x18\x11 \x01(\x02\x12\x30\n\ncut_status\x18\x12 \x01(\x0e\x32\x1c.FusionCommonProto.CutStatus\x12\x34\n\x06status\x18\x13 \x01(\x0e\x32$.FusionCommonProto.ObjectMotionState\x12\x32\n\x0bturn_signal\x18\x14 \x01(\x0e\x32\x1d.FusionCommonProto.TurnSignal\x12=\n\x11obj_measure_state\x18\x15 \x01(\x0e\x32\".FusionCommonProto.ObjMeasureState\x12\x19\n\x11\x66\x63_source_trackid\x18\x16 \x01(\x05\x12\x41\n\x13staticobj_lane_assi\x18\x17 \x01(\x0e\x32$.FusionCommonProto.StaticObjLaneAssi\x12\x33\n\x0b\x62rake_light\x18\x18 \x01(\x0e\x32\x1e.FusionCommonProto.BrakeSignal\"\xd6\x01\n\rFusObjectsMcu\x12\x12\n\ntime_stamp\x18\x01 \x01(\x01\x12\'\n\x04objs\x18\x02 \x03(\x0b\x32\x19.FusionProto.FusObjectMcu\x12\x13\n\x0b\x66rame_index\x18\x03 \x01(\x05\x12,\n\x08ped_data\x18\x04 \x01(\x0b\x32\x1a.FusionCommonProto.PedData\x12\x15\n\rdanger_degree\x18\x05 \x01(\x05\x12.\n\tseqheader\x18\x06 \x01(\x0b\x32\x1b.SeqHeaderProto.DelayHeaderb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fusion_object_mcu_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _FUSOBJECTMCU._serialized_start=80
  _FUSOBJECTMCU._serialized_end=925
  _FUSOBJECTSMCU._serialized_start=928
  _FUSOBJECTSMCU._serialized_end=1142
# @@protoc_insertion_point(module_scope)
