# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: idmap_request_mapinfo.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bidmap_request_mapinfo.proto\x12\x05idmap\"L\n\x0fREQHMIIDMapInfo\x12\x0b\n\x03who\x18\x01 \x01(\t\x12\x15\n\rserial_number\x18\x02 \x01(\r\x12\x15\n\rcircle_radius\x18\x03 \x01(\x05\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'idmap_request_mapinfo_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REQHMIIDMAPINFO._serialized_start=38
  _REQHMIIDMAPINFO._serialized_end=114
# @@protoc_insertion_point(module_scope)
