# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lidar_freespace.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import seq_header_pb2 as seq__header__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15lidar_freespace.proto\x12\x13LidarFreeSpaceProto\x1a\x10seq_header.proto\"\xe8\x01\n\x0e\x46reeSpacePoint\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\t\n\x01z\x18\x03 \x01(\x02\x12\r\n\x05theta\x18\x04 \x01(\x02\x12\x0e\n\x06radius\x18\x05 \x01(\x02\x12\x10\n\x08gridconf\x18\x06 \x01(\x02\x12\x35\n\x04type\x18\x07 \x01(\x0e\x32\'.LidarFreeSpaceProto.CaSegmentationType\x12\r\n\x05z_min\x18\x08 \x01(\x02\x12\r\n\x05z_max\x18\t \x01(\x02\x12\x15\n\rground_height\x18\n \x01(\x02\x12\x18\n\x10\x62\x61\x63kground_ratio\x18\x0b \x01(\x02\"\xc1\x01\n\rFreeSpaceData\x12\x11\n\ttimestamp\x18\x01 \x01(\x01\x12\x36\n\tfreespace\x18\x02 \x03(\x0b\x32#.LidarFreeSpaceProto.FreeSpacePoint\x12\x19\n\x11noise_point_ratio\x18\x03 \x01(\x02\x12\x1b\n\x13ground_point_ration\x18\x04 \x01(\x02\x12-\n\nseq_header\x18\x05 \x01(\x0b\x32\x19.SeqHeaderProto.SeqHeader*\xaa\x01\n\x12\x43\x61SegmentationType\x12\x11\n\rSMALL_VEHICLE\x10\x00\x12\x11\n\rLARGE_VEHICLE\x10\x01\x12\x0e\n\nPEDESTRIAN\x10\x02\x12\x07\n\x03VRU\x10\x03\x12\x0c\n\x08\x42\x41RRINER\x10\x04\x12\r\n\tFREESPACE\x10\x05\x12\r\n\tRAILLINGS\x10\x06\x12\x0e\n\nBACKGROUND\x10\x07\x12\x0b\n\x07OUT_ROI\x10\x08\x12\x0c\n\x08NAN_DATA\x10\tb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'lidar_freespace_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CASEGMENTATIONTYPE._serialized_start=496
  _CASEGMENTATIONTYPE._serialized_end=666
  _FREESPACEPOINT._serialized_start=65
  _FREESPACEPOINT._serialized_end=297
  _FREESPACEDATA._serialized_start=300
  _FREESPACEDATA._serialized_end=493
# @@protoc_insertion_point(module_scope)
