# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: manual_calib.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12manual_calib.proto\x12\x0bManualCalib\" \n\x08ZMFpoint\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\"`\n\tCalibInfo\x12\x14\n\x0cpattern_type\x18\x01 \x01(\r\x12\x16\n\x0evalid_channels\x18\x02 \x01(\r\x12%\n\x06points\x18\x03 \x03(\x0b\x32\x15.ManualCalib.ZMFpointb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'manual_calib_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ZMFPOINT._serialized_start=35
  _ZMFPOINT._serialized_end=67
  _CALIBINFO._serialized_start=69
  _CALIBINFO._serialized_end=165
# @@protoc_insertion_point(module_scope)
