# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: odometry.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ca_appendix_pb2 as ca__appendix__pb2
import header_pb2 as header__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eodometry.proto\x12\x0clocalization\x1a\x11\x63\x61_appendix.proto\x1a\x0cheader.proto\"(\n\x05Point\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\t\n\x01z\x18\x03 \x01(\x01\"8\n\nQuaternion\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\t\n\x01z\x18\x03 \x01(\x01\x12\t\n\x01w\x18\x04 \x01(\x01\"o\n\x04Pose\x12%\n\x08position\x18\x01 \x01(\x0b\x32\x13.localization.Point\x12,\n\nquaternion\x18\x02 \x01(\x0b\x32\x18.localization.Quaternion\x12\x12\n\ncovariance\x18\x03 \x03(\x01\"f\n\x05Twist\x12#\n\x06linear\x18\x01 \x01(\x0b\x32\x13.localization.Point\x12$\n\x07\x61ngular\x18\x02 \x01(\x0b\x32\x13.localization.Point\x12\x12\n\ncovariance\x18\x03 \x03(\x01\"\xbc\x01\n\x08Odometry\x12$\n\x06header\x18\x01 \x01(\x0b\x32\x14.localization.Header\x12\x16\n\x0e\x63hild_frame_id\x18\x02 \x01(\t\x12 \n\x04pose\x18\x03 \x01(\x0b\x32\x12.localization.Pose\x12\"\n\x05twist\x18\x04 \x01(\x0b\x32\x13.localization.Twist\x12,\n\nca_related\x18\x05 \x01(\x0b\x32\x18.localization.CaAppendixb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'odometry_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _POINT._serialized_start=65
  _POINT._serialized_end=105
  _QUATERNION._serialized_start=107
  _QUATERNION._serialized_end=163
  _POSE._serialized_start=165
  _POSE._serialized_end=276
  _TWIST._serialized_start=278
  _TWIST._serialized_end=380
  _ODOMETRY._serialized_start=383
  _ODOMETRY._serialized_end=571
# @@protoc_insertion_point(module_scope)
