# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: point_cloud.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import header_pb2 as header__pb2
import odometry_pb2 as odometry__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11point_cloud.proto\x12\x0clocalization\x1a\x0cheader.proto\x1a\x0eodometry.proto\"\'\n\x07\x43hannel\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0e\n\x06values\x18\x02 \x03(\x01\"\x80\x01\n\nPointCloud\x12$\n\x06header\x18\x01 \x01(\x0b\x32\x14.localization.Header\x12#\n\x06points\x18\x02 \x03(\x0b\x32\x13.localization.Point\x12\'\n\x08\x63hannels\x18\x03 \x03(\x0b\x32\x15.localization.Channelb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'point_cloud_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CHANNEL._serialized_start=65
  _CHANNEL._serialized_end=104
  _POINTCLOUD._serialized_start=107
  _POINTCLOUD._serialized_end=235
# @@protoc_insertion_point(module_scope)
