# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tbox.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ntbox.proto\x12\tTboxProto\"Z\n\x04Tbox\x12)\n\ttbox_time\x18\x01 \x01(\x0b\x32\x16.TboxProto.BusTboxTime\x12\'\n\x08tbox_sts\x18\x02 \x01(\x0b\x32\x15.TboxProto.BusTboxSts\"\xd7\x03\n\nBusTboxSts\x12\x1f\n\x17tbox_apa_control_enable\x18\x01 \x01(\r\x12\x1d\n\x15tbox_apa_function_req\x18\x02 \x01(\r\x12\x1d\n\x15tbox_hzp_function_req\x18\x03 \x01(\r\x12\x1e\n\x16tbox_remote_detect_req\x18\x04 \x01(\r\x12\x1b\n\x13tbox_remote_dis_req\x18\x05 \x01(\r\x12\x1d\n\x15tbox_remote_start_req\x18\x06 \x01(\r\x12\x1c\n\x14tbox_signal_strength\x18\x07 \x01(\r\x12\x18\n\x10tbox_signal_type\x18\x08 \x01(\r\x12%\n\x1dtbox_vehicle_vedio_detect_req\x18\t \x01(\r\x12\x1f\n\x17tbox_hzp_control_enable\x18\n \x01(\r\x12\x12\n\ntime_stamp\x18\x0b \x01(\x01\x12\x17\n\x0ftbox_app_xlevel\x18\x0c \x01(\x01\x12\x17\n\x0ftbox_app_ylevel\x18\r \x01(\x01\x12\x1c\n\x14tbox_apa_signaldelay\x18\x0e \x01(\r\x12\x15\n\rmessage_valid\x18\x0f \x01(\r\x12\x13\n\x0bmqtt_status\x18\x10 \x01(\r\"\xfc\x02\n\x0b\x42usTboxTime\x12\x1a\n\x12tbox_local_ti_date\x18\x01 \x01(\r\x12\x18\n\x10tbox_local_ti_hr\x18\x02 \x01(\r\x12\x1a\n\x12tbox_local_ti_mins\x18\x03 \x01(\r\x12\x19\n\x11tbox_local_ti_mth\x18\x04 \x01(\r\x12\x19\n\x11tbox_local_ti_sec\x18\x05 \x01(\r\x12\x19\n\x11tbox_local_ti_vld\x18\x06 \x01(\r\x12\x1a\n\x12tbox_local_ti_year\x18\x07 \x01(\r\x12\x12\n\ntime_stamp\x18\x08 \x01(\x01\x12\x15\n\rmessage_valid\x18\t \x01(\r\x12\x11\n\treserved0\x18\n \x01(\r\x12\x11\n\treserved1\x18\x0b \x01(\r\x12\x11\n\treserved2\x18\x0c \x01(\r\x12\x11\n\treserved3\x18\r \x01(\r\x12\x11\n\treserved4\x18\x0e \x01(\r\x12\x11\n\treserved5\x18\x0f \x01(\r\x12\x11\n\treserved6\x18\x10 \x01(\rb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tbox_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TBOX._serialized_start=25
  _TBOX._serialized_end=115
  _BUSTBOXSTS._serialized_start=118
  _BUSTBOXSTS._serialized_end=589
  _BUSTBOXTIME._serialized_start=592
  _BUSTBOXTIME._serialized_end=972
# @@protoc_insertion_point(module_scope)
