# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: throass.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rthroass.proto\x12\x0cThroAssProto\"\x9a\x01\n\rThroAssStatus\x12 \n\x18\x61\x63\x63r_pedal_frnt_actv_sts\x18\x01 \x01(\r\x12 \n\x18\x61\x63\x63r_pedal_rear_actv_sts\x18\x02 \x01(\r\x12\x1c\n\x14thro_open_inhibi_val\x18\x03 \x01(\x02\x12\'\n\x1f\x61\x63\x63r_pedal_frnt_rear_shadow_sts\x18\x04 \x01(\rb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'throass_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _THROASSSTATUS._serialized_start=32
  _THROASSSTATUS._serialized_end=186
# @@protoc_insertion_point(module_scope)
