# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vp_parsing_setting.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import vp_perception_base_pb2 as vp__perception__base__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18vp_parsing_setting.proto\x12\x15VpParsingSettingProto\x1a\x18vp_perception_base.proto\"(\n\x05\x43olor\x12\t\n\x01\x62\x18\x01 \x01(\r\x12\t\n\x01g\x18\x02 \x01(\r\x12\t\n\x01r\x18\x03 \x01(\r\"8\n\x10RuntimeModelInfo\x12\x10\n\x08model_id\x18\x01 \x01(\x05\x12\x12\n\nmodel_name\x18\x02 \x01(\t\"\xe7\x03\n\x0eParsingSetting\x12-\n\x06header\x18\x14 \x01(\x0b\x32\x1d.VpPerceptionBaseProto.Header\x12\x14\n\x0cparsing_type\x18\x01 \x01(\x05\x12\x18\n\x10parsing_channels\x18\x02 \x01(\x05\x12\x16\n\x0e\x63hannel_labels\x18\x03 \x03(\x04\x12\x34\n\x0e\x63hannel_colors\x18\x04 \x03(\x0b\x32\x1c.VpParsingSettingProto.Color\x12\x1a\n\x12\x66reespace_channels\x18\x05 \x03(\x05\x12\x1b\n\x13\x62oundspace_channels\x18\x06 \x03(\x05\x12\x30\n\x0bparsing_roi\x18\x07 \x01(\x0b\x32\x1b.VpPerceptionBaseProto.Rect\x12\x15\n\rparsing_scale\x18\x08 \x01(\x02\x12;\n\nmodel_info\x18\t \x03(\x0b\x32\'.VpParsingSettingProto.RuntimeModelInfo\x12\x12\n\ntime_stamp\x18\n \x01(\x03\x12\x0e\n\x06\x63\x61m_id\x18\x0b \x01(\x05\x12\x10\n\x08\x66rame_id\x18\x0c \x01(\x05\x12\x33\n\ncategories\x18\r \x03(\x0b\x32\x1f.VpPerceptionBaseProto.Category*V\n\x0bParsingType\x12\x18\n\x14PARSING_TYPE_DEFAULT\x10\x00\x12\x15\n\x11PARSING_TYPE_LANE\x10\x01\x12\x16\n\x12PARSING_TYPE_DEPTH\x10\x02')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vp_parsing_setting_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PARSINGTYPE._serialized_start=667
  _PARSINGTYPE._serialized_end=753
  _COLOR._serialized_start=77
  _COLOR._serialized_end=117
  _RUNTIMEMODELINFO._serialized_start=119
  _RUNTIMEMODELINFO._serialized_end=175
  _PARSINGSETTING._serialized_start=178
  _PARSINGSETTING._serialized_end=665
# @@protoc_insertion_point(module_scope)
