# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vp_parsing.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import vp_image_pb2 as vp__image__pb2
from vp import camera_pb2 as vp_dot_camera__pb2
import vp_parsing_setting_pb2 as vp__parsing__setting__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10vp_parsing.proto\x12\x0eVpParsingProto\x1a\x0evp_image.proto\x1a\x0fvp.camera.proto\x1a\x18vp_parsing_setting.proto\"@\n\tElevation\x12\x1c\n\x14ground_normal_vector\x18\x01 \x03(\x02\x12\x15\n\rheight_ranges\x18\x02 \x03(\x02\"?\n\nBevSetting\x12\x1a\n\x12spatial_resolution\x18\x01 \x03(\x02\x12\x15\n\rvisible_range\x18\x02 \x03(\x02\"\xd6\x01\n\x0c\x44\x65pthSetting\x12\x14\n\x0cscale_number\x18\x01 \x01(\x02\x12\x13\n\x0bshift_scale\x18\x02 \x01(\x02\x12\x14\n\x0cmapping_type\x18\x03 \x01(\r\x12\x15\n\rmapping_shift\x18\x04 \x01(\r\x12\x18\n\x10\x63onfidence_scale\x18\x05 \x01(\x02\x12\x11\n\tmax_depth\x18\x06 \x01(\x02\x12\x11\n\tmin_depth\x18\x07 \x01(\x02\x12\x16\n\x0emax_confidence\x18\x08 \x01(\x02\x12\x16\n\x0emin_confidence\x18\t \x01(\x02\"\x81\x02\n\x07Parsing\x12\"\n\x05image\x18\x01 \x01(\x0b\x32\x13.VpImageProto.Image\x12>\n\x0fparsing_setting\x18\x02 \x01(\x0b\x32%.VpParsingSettingProto.ParsingSetting\x12,\n\televation\x18\x03 \x01(\x0b\x32\x19.VpParsingProto.Elevation\x12/\n\x0b\x62\x65v_setting\x18\x04 \x01(\x0b\x32\x1a.VpParsingProto.BevSetting\x12\x33\n\rdepth_setting\x18\x05 \x01(\x0b\x32\x1c.VpParsingProto.DepthSettingb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vp_parsing_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ELEVATION._serialized_start=95
  _ELEVATION._serialized_end=159
  _BEVSETTING._serialized_start=161
  _BEVSETTING._serialized_end=224
  _DEPTHSETTING._serialized_start=227
  _DEPTHSETTING._serialized_end=441
  _PARSING._serialized_start=444
  _PARSING._serialized_end=701
# @@protoc_insertion_point(module_scope)
